### ISSUE TITLE
2022.4.2: Cannot load KernelManager.dll - not a valid shared library. Cannot continue!

### ISSUE THREAD

**Issue by UselessGuru** [TrailingStop/TT-Miner-release#1]
TT-Miner.exe -algo GhostRider -pool stratum+tcp://ghostrider.eu.mine.zpool.ca:5354 -user *************************** -pass ******************,c=BTC -PRT 1 -PRS 0 -api-bind 127.0.0.1:4006 -device 1

19:53:22 ********* TT-Miner - Version: 2022.4.2 (Dec 18 2022 18:43:39)
19:53:22 ********* Log system initialized...
19:53:22 ********* Internal event system initialized...
19:53:22 ********* Worker threads initialized, using 6 threads...
19:53:22 Cannot load KernelManager.dll - not a valid shared library. Cannot continue!
19:53:22 ********* Stop worker threads...
19:53:22 ********* Internal event system stopped and destroyed...
19:53:22 ********* All threads stopped and destroyed...

Same error with all algorithms

**Comment by TrailingStop** [comment]
Hi - cannot reproduce the problem. Have you used a new empty folder to extract the new version?
Please compare you files with the these details:
![image](https://user-images.githubusercontent.com/39515115/208314620-429d3040-1d1b-4605-a5bf-4797577d597c.png)

**Comment by UselessGuru** [comment]
> Maybe it is because cuda 12. Do you have latest nvidia driver?

No, I am still on cuda 11.7. Can you please compile versions for older drivers too. Thank you!

**Comment by TrailingStop** [comment]
Sure- one sec

**Comment by TrailingStop** [comment]
Can you please check if TT works with this exe?
[TT-Miner.zip](https://github.com/TrailingStop/TT-Miner-release/files/10254475/TT-Miner.zip)

**Comment by UselessGuru** [comment]
New exe is working.

However:
**1. ProgPowZ is not working (tested with GTX1660 Super, GT1030 and GTX750ti).** 

`TT-Miner.exe -algo ProgPowZ -coin ZANO -dag-2disk -pool stratum+tcp://progpowz.mine.zergpool.com:3003 -user ******************-pass *********,c=BTC,pl=0 -api-bind 127.0.0.1:4005 -devices 1`

I get:

23:41:21 ********* Start mining
23:41:21 ********* Mining fee for 'Zano': 1.00%
23:41:21 ********* Start worker loop...
23:41:21 Pool[ZANO-0]:  Connecting to: stratum+tcp://progpowz.mine.zergpool.com:3003
23:41:21 Pool[ZANO-0]:  Connected to: progpowz.mine.zergpool.com:3003 - IP4/IP6: 103.249.70.7
**23:41:21 Pool[ZANO-0]:  Invalid method - Function: SUBSCRIBE**
23:41:21 Miner:         Exit, start cleanup... TT-Miner

Other miners, e.g. WildRig work fine.

**2. Milke & Ghostrider don't work on my GTX750ti (2GB).** 
3GT1030 (2GB) is working. TTMiner starts without any error messages, but it newer produces any hashrates.

Is this a known issue?

**Comment by TrailingStop** [comment]
Try: TT-Miner.exe -algo ProgPowZ -coin ZANO -dag-2disk -pool stratum1+tcp://progpowz.mine.zergpool.com:3003 -user ******************-pass *********,c=BTC,pl=0 -api-bind 127.0.0.1:4005 -devices 1

**Comment by UselessGuru** [comment]
> Try: TT-Miner.exe -coin ZANO -dag-2disk -pool progpowz.mine.zergpool.com:3003 -user ******************-pass *********,c=BTC,pl=0 -api-bind 127.0.0.1:4005 -devices 1

Same problem.

**Comment by TrailingStop** [comment]
try -P stratum1-tcp://pool progpowz.mine.zergpool.com:3003

**Comment by UselessGuru** [comment]
> try -P stratum1-tcp://pool progpowz.mine.zergpool.com:3003

That works. Please update the documentation.
