### ISSUE TITLE
TT-Miner fastepic.eu command line.

### ISSUE THREAD

**Issue by fastepic** [TrailingStop/TT-Miner-release#10]
In TT-Miner -coin EPIC -P ssl://<YOUR_KEYBASE_ID>.<YOUR_WORKER_NAME>:<YOUR_PASSWORD>@fastepic.eu:3416    could  be TT-Miner -coin EPIC -P ssl://keybaseid_<YOUR_KEYBASE_ID>.<YOUR_WORKER_NAME>:<YOUR_PASSWORD>@fastepic.eu:3416

**Comment by TrailingStop** [comment]
Will change - thanks for the information.

**Comment by TrailingStop** [comment]
Done - hope I made all required changed? Let me know if you see more.

**Comment by fastepic** [comment]
Hmmm why I see ssl://\keybaseid_... ? ssl://keybaseid_... is correct ...

**Comment by fastepic** [comment]
Looks OK now. Thanks.
