### ISSUE TITLE
support ZIL

### ISSUE THREAD

**Issue by totosugito** [TrailingStop/TT-Miner-release#12]
Hi,
Thank you for the great miner app.
Can you add ZIL support in the app?
So, we can triple mining together. 
Example : 
Primary : EPIC
Secondary (alt) : ETC
Third : ZIL

Thank you

**Comment by TrailingStop** [comment]
Hi- thanks for your support of TT. This is exactly what I'm working on. Next beta will do that.

**Comment by totosugito** [comment]
Great...
Thank you for the fast response.
Waiting for the new release ... :)

**Comment by TrailingStop** [comment]
supported in new beta - 2023.2.0. At the moment windows only, Linux will follow soon.

**Comment by TrailingStop** [comment]
Linux beta version with ZIL support is ready for testing:
https://github.com/TrailingStop/TT-Miner-beta
