### ISSUE TITLE
 Invalid method - Function: SUBSCRIBE

### ISSUE THREAD

**Issue by Schneideisen** [TrailingStop/TT-Miner-release#14]
17:07:15.798 ********* Start mining
17:07:15.799 ********* Mining fee for 'ProgPoWZ': 1.00%
17:07:15.800 ********* Start worker loop...
17:07:16.446 Pool[DEF-0]:   Connecting to: stratum+tcp://progpowz.mine.zergpool.com:3003
17:07:20.823 Pool[DEF-0]:   Connected to: progpowz.mine.zergpool.com:3003 - IP4/IP6: 103.249.70.7
17:07:20.082 Pool[DEF-0]:   Invalid method - Function: SUBSCRIBE
17:07:20.082 Miner:         Exit, start cleanup... TT-Miner
17:07:20.085 Miner:         Notify Statistics to stop
17:07:20.086 Miner:         Notify DevFeeManager to stop
17:07:20.087 Miner:         Notify KernelManager to stop
17:07:20.088 Miner:         Notify DagManager to stop
17:07:20.089 Miner:         Notify algos to stop
17:07:20.089 Miner:         Notify sockets to atop
17:07:20.089 Miner:         Exit Statistics
17:07:20.091 Miner:         Exit KernelManager
17:07:20.092 Miner:         Exit DagManager
17:07:20.093 Miner:         All Sockets stopped and unloaded
17:07:20.094 Miner:         All Algos stopped and unloaded
17:07:20.094 Miner:         Exit all Sockets
17:07:20.095 Miner:         Exit all Algos

**Comment by TrailingStop** [comment]
Hi - you need to connect to "stratum1+tcp" - not startum+tcp.
If you have issues to set this up please share your commandline so that I can change it for you.

**Comment by Schneideisen** [comment]
ok work with "stratum1+tcp"
