### ISSUE TITLE
Added "oc_core_clock_offset"

### ISSUE THREAD

**Issue by totosugito** [TrailingStop/TT-Miner-release#15]
Hi,
Thank you for the great app
Can you add the parameter for "oc_core_clock_offset" for the app?
Thank you.
Best regards,

Toto

**Comment by totosugito** [comment]
Are you mean like this for main and alternatif coin parameter ?
Main coin :
-oc-core-off  MY_VALUE

Alternatif coin
-oc-core-offalt  MY_VALUE

I am use hiveos.
Thank you

**Comment by TrailingStop** [comment]
Yes- exactly

**Comment by TrailingStop** [comment]
TT-Miner 2023.2.0 beta 2 support now core/mem offset settings

**Comment by totosugito** [comment]
I am waiting for the linux version because use Hive. When you release the linux version ? Thank you very much

**Comment by TrailingStop** [comment]
Very soon - already working on linux.

**Comment by TrailingStop** [comment]
should work in the latest release version - please check
