### ISSUE TITLE
Pool[ZANO-0]:  Invalid method - Function: SUBSCRIBE

### ISSUE THREAD

**Issue by 1TurdBucket** [TrailingStop/TT-Miner-release#17]
Awesome miner Dev!  Thank you. Is there a TT-Miner 2023.2.0?

Miner was mining Kawpow on ZergPool with no errors. I tried mining ProPowZ and getting this error message: "Pool[ZANO-0]:  Invalid method - Function: SUBSCRIBE." 
<img width="1173" alt="Screenshot 2023-04-24 at 12 35 22 PM" src="https://user-images.githubusercontent.com/129686695/234088209-96c01ac4-dcfa-428d-9a1e-d5bf25c98c04.png">
<img width="269" alt="Screenshot 2023-04-24 at 12 37 28 PM" src="https://user-images.githubusercontent.com/129686695/234088246-68b75ce2-13d3-4506-a792-f90639ad592c.png">

**Comment by TrailingStop** [comment]
Hi - for zano you need stratum1. Please change the protocol in your URL settings to stratum1+tcp - or if you prefer SSL change it to stratum1+ssl and use port 13003. Please let me know if this fixes the problem.

**Comment by 1TurdBucket** [comment]
That fix worked.  Thank you.
 
<img width="1509" alt="Screenshot 2023-04-24 at 2 06 08 PM" src="https://user-images.githubusercontent.com/129686695/234104865-58e21d38-7662-4418-a71c-fee2b8c9e729.png">
