### ISSUE TITLE
memory clock offset don`t work in TT-Miner - Version 2023.4.0

### ISSUE THREAD

**Issue by Vortex16vt** [TrailingStop/TT-Miner-release#19]
memory clock offset (-oc-memoff) don`t work in TT-Miner - Version 2023.4.0

work with same command in TT-Miner - Version 2023.3.0

**Comment by TrailingStop** [comment]
Hi- can you  plewase check this new beta ands let me know if you still see the bug?
www.TradeProject.de/download/Miner/TT-Miner-2023.4.1b1.Hive.tar.gz
www.TradeProject.de/download/Miner/TT-Miner-2023.4.1b1.tar.gz
www.TradeProject.de/download/Miner/TT-Miner-2023.4.1b1.zip

**Comment by Vortex16vt** [comment]
In this version memory clock offset (-oc-memoff) WORK.

**Comment by TrailingStop** [comment]
OK- thanks for the feedback.
