### ISSUE TITLE
TT-Miner crashes if "-w[...]" is set

### ISSUE THREAD

**Issue by RainbowMiner** [TrailingStop/TT-Miner-release#21]
TT-Miner v2023.4.1 / Windows / RTX3070

As the title says, the miner immediately after the start, if I use "-w[...]" parameter for workername. I have tried  it on ZergPool, Zpool and MoneroOcean. All the same result.

```
15:48:56.603 ********* TT-Miner - Version: 2023.4.1 (Sep 15 2023 03:03:28)
15:48:56.603 ********* Log system initialized...
15:48:56.603 ********* Internal event system initialized...
15:48:56.603 ********* Worker threads initialized, using 4 threads...
15:48:56.611 ********* Commandline: TT-Miner.exe --api-bind 127.0.0.1:33333 -d 6 -dag-2disk -daginfo -Pcl stratum+tcp://hereismyxmraddress:rtx~kawpow@gulf.moneroocean.stream:10032 -wcl rtx -ccl CLORE -cz ZIL -Pz hereismyziladdress.rtx:x@eu.crazypool.org:5005 -acl KawPow
15:48:58.434 ********* Stop worker threads...
15:48:58.435 ********* Internal event system stopped and destroyed...
15:48:58.435 ********* All threads stopped and destroyed...
```

If I remove the -wcl, the miner runs fine.

**Comment by TrailingStop** [comment]
Hi- yes. if you use -P then you do not need -w or -p or -o. The format is always the same:
-P[...] wallet.worker:password@server:port
If you use -c[...] you do not need to set any algo

So for clore you just need -ccl CLORE -Pcl hereismyxmraddress:rtx~kawpow@gulf.moneroocean.stream:10032
TT will take hereismyxmraddress as wallet-id, and rtx~kawpow as your password. You did not specify the worker:

This alone should be ok for clore: -Pcl hereismyxmraddress.rtx~kawpow@gulf.moneroocean.stream:10032 -ccl CLORE
Zil is OK: -cz ZIL -Pz hereismyziladdress.rtx:x@eu.crazypool.org:5005

**Comment by RainbowMiner** [comment]
The `rtx~kawpow` is the password for this pool. The pool wants the workername in the password field along the algorithm, separated by ~.

So what do you pass through to the pools exactly? Do you send `walletaddress.workername` or do you parse it first and then send `walletaddress` and then `workername` with the stratum protocol?

**Comment by TrailingStop** [comment]
Yes - all information fits into the -P option:

-P[...] <walletaddress>.<workername>:<password>@<server>:<port>
if you use ssl:
-P[...] ssl://<walletaddress>.<workername>:<password>@<server>:<port>

**Comment by trampk** [comment]
> Yes - all information fits into the -P option:
> 
> -P[...] .:@: if you use ssl: -P[...] ssl://.:@:
> 
> If it is easier for you, you can use -o, -w, -p instead of -P
> 
> Yes. I parse the -P settings and use stratum protocol

Hi! How can I set overclocking settings for every algo?

TT-Miner.exe -cEP EPIC -PEP wallet.worker@mynode:port -crt RTM -Prt wallet.worker:password@mypool:port -cz ZIL -Pz wallet.worker:password@eu.crazypool.org:5005 -oc-core 1455 -oc-memoff 1000 -oc-coreoff 200

now error selector "DEF" not found

or for this example?

TT-Miner.exe -cEP EPIC -PEP wallet.worker@mynode:port -a ALGO wallet.worker:password -o mypool:port -cz ZIL -Pz wallet.worker:password@eu.crazypool.org:5005 -oc-core 1455 -oc-memoff 1000 -oc-coreoff 200

without settings OC all working fine,  but overclocking is not applied to EPIC algo, only fo 2 algo

How would you like to do something like this?

for algo 1 (EPIC)
-oc-core1 1455 -oc-memoff1 1000 -oc-coreoff1 200
for algo 2 (Any algo)
-oc-core2 1860 -oc-memoff2 1000 -oc-coreoff2 255
for algo 3 (ZIL)
-oc-core3 1200 -oc-memoff3 1000 -oc-coreoff3 255

**Comment by TrailingStop** [comment]
Just use the same selector as you use for all other. For example. You use EP for 3epic, then your oc would look like this:
-oc-coreEC 1455 -oc-memoffEC 1000 -oc-coreoffEC 200
Zil the same - use 'z' as selector:
-oc-corez 1860 
and so on
