### ISSUE TITLE
doesn't start mining Erica on 3070

### ISSUE THREAD

**Issue by Alirezazaktab110** [TrailingStop/TT-Miner-release#24]
rtx3070, win 11 pro 21H2 64bit
this is my bat file and I start it as an administrator 
TT-Miner.exe -c ETI -P 0x2e2b0E8Bec326F99De42C713C0D18D39779CFCb9.RTX3070Roglin:x@http://0xpool.io:80 -raao -oc-coreDEF 1470 -oc-coreoffDEF 325 -oc-memoffDEF 100 -oc-plDEF W170
it doesn't start mining
I think I have same issue on 2023.4.1 with ghostrider algo and suddenly after some hours and a .gcf file created in gpu config folder and it started working. I don't know its normal or should i change something?
thanks.

**Comment by TrailingStop** [comment]
Hi - please try this commandline:
TT-Miner.exe -c ETI -P 0x2e2b0E8Bec326F99De42C713C0D18D39779CFCb9.RTX3070Roglin:x@0xpool.me:80 -raao -oc-core 1470 -oc-coreoff 325 -oc-memoff 100 -oc-pl W170
[11:16 AM]
-your pools settings were not correct
-DEF is not required outside of hive for a single coin mining

**Comment by Alirezazaktab110** [comment]
thanks alot god bless you TrailingStop. you solved the problem
