### ISSUE TITLE
v2023.4.2 (Windows): Error mining NOVO@ZergPool on GTX1660 Super

### ISSUE THREAD

**Issue by UselessGuru** [TrailingStop/TT-Miner-release#25]
`TTMiner-v2023.4.2\TT-Miner.exe -c NOVO -P stratum+tcp://*******************:c=BTC,mc=NOVO,ID=********************@sha256dt.eu.mine.zergpool.com:3341 -no-hashrate -b 127.0.0.1:7 -d 0`

13:18:42.208 ********* TT-Miner - Version: 2023.4.2 (Nov 25 2023 11:36:28)
13:18:42.208 ********* Log system initialized...
13:18:42.208 ********* Internal event system initialized...
13:18:42.208 ********* Worker threads initialized, using 6 threads...
13:18:42.221 ********* Commandline: Bin\TTMiner-v2023.4.2\TT-Miner.exe -c NOVO -P stratum+tcp://******************************:c=BTC,mc=NOVO,ID=****************@sha256dt.eu.mine.zergpool.com:3341 -no-hashrate -b 127.0.0.1:7 -d 0
13:18:43.068 ********* CUDA-GPU information
13:18:43.068 GeForce Driver-Ver:    546.01
13:18:43.070 NVML-Ver:              12.546.01
13:18:43.070 CUDA-Ver:              12.3
13:18:43.071
13:18:43.072       CUDA devices:    3
13:18:43.072 * #00 PCI 11:00.0 MSI        NVIDIA GeForce GTX 1660 SUPER  6.000 GB / 5.778 GB  SM/Cores: 22/1408   {E313803C-A07D-9F5E-859B-D0FE69B3864C}
13:18:43.073                              Supported MemClk lock(-oc-mem): 405, 810, 5001, 6801, 7001
13:18:43.073   #01 PCI 12:00.0 ASUS       NVIDIA GeForce GT 1030         2.000 GB / 436.8 MB  SM/Cores: 3/384     {CE27AC47-93CD-5890-14F4-1CB6A6347701}
13:18:43.074                              Supported MemClk lock(-oc-mem): 405, 810, 3004
13:18:43.074   #02 PCI 16:00.0 Gainward   NVIDIA GeForce GTX 750 Ti      2.000 GB / 1.933 GB  SM/Cores: 5/640     {A5B40D91-D3A4-1E1E-4EA8-6848C00804FD}
13:18:43.075                              Supported MemClk lock(-oc-mem): 405, 3225
13:18:43.075
13:18:43.076
13:18:43.076 Algo-1 "DEF":          auto detect from coin
13:18:43.077              -Algo:    SHA256DT
13:18:43.078              -Coin:    Novo (NOVO)
13:18:43.079 Primary server:        sha256dt.eu.mine.zergpool.com:3341 - SocketStratum
13:18:43.079              -Wallet:  1GPSq8txFnyrYdXL8t6S94mYdF8cGqVQJF
13:18:43.079              -Worker:
13:18:43.080              -Pwd:     c=BTC,mc=NOVO,ID=Blackbox
13:18:43.080
13:18:43.081 ********* Hash speed reporting
13:18:43.081 Avg. performance time frame:   1 minute
13:18:43.083 Performance summary(sec.):     15 seconds
13:18:43.088 Performance summary(shares):   disabled
13:18:43.092
13:18:43.092 ********* Apply settings
13:18:43.092 Temp control:                  disabled
13:18:43.100 API-Interface:                 listening on 127.0.0.1:7, WebStatus refresh disabled.
13:18:43.102 Broadcast hashrate:            disabled
13:18:43.104
13:18:43.107 ***
13:18:43.108
13:18:43.111
13:18:43.111  _______ _______     __  __ _____ _   _ ______ _____
13:18:43.112 |__   __|__   __|   |  \/  |_   _| \ | |  ____|  __ \
13:18:43.113    | |     | |______| \  / | | | |  \| | |__  | |__) |
13:18:43.114    | |     | |______| |\/| | | | | . ` |  __| |  _  /
13:18:43.115    | |     | |      | |  | |_| |_| |\  | |____| | \ \
13:18:43.120    |_|     |_|      |_|  |_|_____|_| \_|______|_|  \_\
13:18:43.122
13:18:43.123
13:18:43.123 ***
13:18:43.124 Version: TT-Miner (2023.4.2 Nov 25 2023)
13:18:43.125 Get 20% discount on your Binance Exchange trading fees and support TT-Miner
13:18:43.126   TT  / You          link
13:18:43.126  20%     0%          https://accounts.binance.com/en/register?ref=28122598
13:18:43.126  15%     5%          https://accounts.binance.com/en/register?ref=UJPASPV6
13:18:43.127  10%    10%          https://accounts.binance.com/en/register?ref=LAUV5U9I
13:18:43.128 ***
13:18:43.128
13:18:43.129
13:18:43.136 ********* Press 'x' to enter menu
13:18:43.138
13:18:43.139
13:18:43.139
13:18:43.140
13:18:43.140 ********* DevFee: 1.00%
13:18:43.141
13:18:43.142 ********* Start API Monitor Listener @ 127.0.0.1:7
13:18:43.142 ********* Start mining
13:18:43.143
13:18:43.289 Algo:          Active algo: Novo / SHA256DT - switch #1
13:18:43.289 Pool[NOVO-0]:  *Connected to stratum+tcp://sha256dt.eu.mine.zergpool.com:3341 [141.95.55.97].
13:18:43.338 Pool[NOVO-0]:  *Set pool extra nonce to: 0x23460081
13:18:43.436 Pool[NOVO-0]:  *Difficulty set to 8.590 GH
13:18:43.436 Pool[NOVO-0]:  *Received new job#: 666
13:18:43.436 Pool[NOVO-0]:  *Working on Block#: 437440
13:18:44.300 Krnl[00-NOVO]: *Create CUDA-Kernel configuration (CU_G-A144#0-75) for compute 7.5
**13:18:44.321 Krnl[00-NOVO]: *Cannot configure CUDA-Kernel (CU_G-A144#0-75) for compute 7.5**

Same commands work on GTX750 & GT1030.

**Comment by UselessGuru** [comment]
Same error

**Comment by TrailingStop** [comment]
new version with the fix is not released yet.

**Comment by UselessGuru** [comment]
> new version with the fix is not released yet.

I know - but I reported it so you can also fix it in the coming release.

**Comment by UselessGuru** [comment]
> i  developed the bug

Nice typo ;-) I don't think this is exactly what you meant to say.

**Comment by TrailingStop** [comment]
Most likely not - but I hope you got my point?

**Comment by TrailingStop** [comment]
Hi - new version with the fix is available now. Thanks again for testing & reporting!

**Comment by UselessGuru** [comment]
Fixed in 2023.4.3.
