### ISSUE TITLE
Pool connection issue - SSL Routines

### ISSUE THREAD

**Issue by Wallabie123** [TrailingStop/TT-Miner-release#26]
Error connecting to pools related to SSL. Same issue regardless of which pool I try to connect to.

![image](https://github.com/TrailingStop/TT-Miner-release/assets/46752160/79941837-1958-4e45-a8d9-40b7138e57b4)

**Comment by TrailingStop** [comment]
ssl on 0xpool.io uses port 443. port 80 is tcp.

**Comment by Wallabie123** [comment]
Thank you! I'm not sure where you found this - I don't see that anywhere on the pool site.

**Comment by TrailingStop** [comment]
http is in most cases port 80 which https is in most cases port 443. I know that the pool uses http - so that's why.
