### ISSUE TITLE
Sorry,why no Hashrate?

### ISSUE THREAD

**Issue by abc5692563** [TrailingStop/TT-Miner-release#28]
why no Hashrate?
my configuration
![1701361990218](https://github.com/TrailingStop/TT-Miner-release/assets/74282332/41c847cc-d167-4c56-b85e-9cc65d938fbc)
![1701362038222](https://github.com/TrailingStop/TT-Miner-release/assets/74282332/46a05f1a-69e0-43ee-b840-9457aba1ac4f)

**Comment by TrailingStop** [comment]
remove the http:// from the pool url and add -c ETI to your custom options

**Comment by abc5692563** [comment]
> remove the http:// from the pool url and add -c ETI to your custom options

sorry,bro
is same,no Hashrate
![1701363821636](https://github.com/TrailingStop/TT-Miner-release/assets/74282332/14d16483-afcf-420f-a3d2-3546b3eca7d5)
![1701363839388](https://github.com/TrailingStop/TT-Miner-release/assets/74282332/dbaa238f-1e30-4a01-8784-25d047a4c63d)

**Comment by TrailingStop** [comment]
now i can see that you use an old nvidia driver - please update and it should work.

**Comment by ebayzir** [comment]
I get the same error in simplemining, what should I write on the command line?

**Comment by ebayzir** [comment]
-a SHA3SOLIDITY -o 0xpool.me:80 -u 0xE0B8525729E4b49eb68903A2d02E8CD8Cf7cBc1C -w $rigName -p x --api-bind 127.0.0.1:3333 my command line is like this

**Comment by TrailingStop** [comment]
did you install the latest nvidia driver? Does it work or not? 

typical commandline for ETI:

TT-Miner -c ETI -P  0xE0B8525729E4b49eb68903A2d02E8CD8Cf7cBc1C.$rigName:x@0xpool.me:80 --api-bind 127.0.0.1:3333

**Comment by ebayzir** [comment]
18:32:58.017 ********* TT-Miner - Version: 2023.4.3 (Nov 28 2023 05:38:47)

18:32:58.017 ********* Log system initialized...

18:32:58.017 ********* Internal event system initialized...

18:32:58.017 ********* Worker threads initialized, using 4 threads...

18:32:58.019 ********* Commandline: /root/miner/tt-miner-v2023.4.3-cuda12.2/TT-Miner -c ETI -P 0xE0B8525729E4b49eb68903A2d02E8CD8Cf7cBc1C.3060 -o 0xpool.me:80 --api-bind 127.0.0.1:3333

18:33:04.936 ********* Stop worker threads...

18:33:04.936 ********* Internal event system stopped and destroyed...

18:33:04.936 ********* All threads stopped and destroyed...

Miner ended or crashed. Restarting miner in 30 seconds...

Now I got this error, I think it's from the OC settings

**Comment by TrailingStop** [comment]
i do not see oc settings

**Comment by ebayzir** [comment]
![Uploading Ekran görüntüsü 2023-11-30 203728.png…]()

**Comment by TrailingStop** [comment]
cannot open

**Comment by ebayzir** [comment]
no I use simpleminig

**Comment by ebayzir** [comment]
can you rewrite the command line

**Comment by TrailingStop** [comment]
easiest way to find out is to remove all OC and then activate again step by step

**Comment by TrailingStop** [comment]
This?
TT-Miner -c ETI -P 0xE0B8525729E4b49eb68903A2d02E8CD8Cf7cBc1C.$rigName:[x@0xpool.me](mailto:x@0xpool.me):80 --api-bind 127.0.0.1:3333
