### ISSUE TITLE
v2023.1.0 (Windows) sha512256d: End of file [asio.misc:2 at win_iocp_socket_recv_op.hpp:89:33 in function 'do_complete'] - func:3

### ISSUE THREAD

**Issue by UselessGuru** [TrailingStop/TT-Miner-release#3]
**20:45:58 ********* Start API Monitor Listener
20:45:58 ********* Start mining
20:45:58 ********* Mining fee for 'Sha512256D': 1.00%
20:45:58 ********* Start worker loop...
20:45:58 Pool[DEF-0]:   Connecting to: stratum+tcp://sha512256d.eu.mine.zpool.ca:3342
20:45:58 Pool[DEF-0]:   Connected to: sha512256d.eu.mine.zpool.ca:3342 - IP4/IP6: 198.50.168.213
**20:45:58 Pool[DEF-0]:   End of file [asio.misc:2 at win_iocp_socket_recv_op.hpp:89:33 in function 'do_complete'] - func:3**
20:45:58 Pool[DEF-0]:   Retry to connect in 15 seconds.
20:45:58 Pool[DEF-0]:   Disconnected from: sha512256d.eu.mine.zpool.ca:3342 - IP4/IP6: 198.50.168.213**

Nvidia RX1660Super
Command line used:
**TT-Miner.exe -algo Sha512256D -pool stratum+tcp://sha512256d.eu.mine.zpool.ca:3342 -user ###########################-pass #########,c=BTC -api-bind 127.0.0.1:4006 -devices 0**

**Comment by TrailingStop** [comment]
Hi - can you please check again with the latest version 2023.1.1?

**Comment by UselessGuru** [comment]
Fixed with 2023.1.1
