### ISSUE TITLE
OC settings doesn't apply

### ISSUE THREAD

**Issue by drond1** [TrailingStop/TT-Miner-release#32]
Hi, have a problem with OC settings in bat file in win10, and also in hiveOS. OC settings doesn't apply. For example:  TT-Miner.exe -cETI ETI -PETI adress.worker@0xpool.io:80 -oc-coreETI [2400] -oc-coreoffETI [300] and + zil. And in miner or in MSI Afterburner I can see, that there is no effect. Driver and miner - latest version.

**Comment by TrailingStop** [comment]
Hi, you need to start the miner as Administrator under Windows to enable OC. Also please remove [] from your OC values

**Comment by drond1** [comment]
thx for your help!

**Comment by drond1** [comment]
hello again, in hiveOS stiil a problem. 
![изображение](https://github.com/TrailingStop/TT-Miner-release/assets/99704990/2497916b-b150-4458-99b4-bc7b0cf9308a)
![изображение](https://github.com/TrailingStop/TT-Miner-release/assets/99704990/2c2e3a69-0355-4e53-99b1-36e3946a3a1d)

**Comment by drond1** [comment]
yep, thx)
