### ISSUE TITLE
Multiple GPU and Wattage example.

### ISSUE THREAD

**Issue by bidgbob** [TrailingStop/TT-Miner-release#35]
Hey TrailingStop,

I'm currently trying to setup a rig for mining ETI. I have 6 GPUs: 1 3090, 1 3070 and 4 3060ti.

OS: HiveOS

I've tried to create a command line line in the flight sheet. But I'm finding the arguments difficult to understand.

This is my current setup in HiveOS. 

![image](https://github.com/TrailingStop/TT-Miner-release/assets/6987090/f1c53089-27ae-45f0-af71-730620145d1b)

Would be great to get an example of how this would be setup for future reference

Thanks

**Comment by TrailingStop** [comment]
Hi- just remove [ and ] and replace , with a space as separator. Place the W of oc-pl after the number like -oc-pl 300W 170W 170W etc....

**Comment by bidgbob** [comment]
That works! Although I am getting a red warning back

![image](https://github.com/TrailingStop/TT-Miner-release/assets/6987090/45ed91de-6916-4a5d-b6a2-a5a67d3ea98b)

**Comment by bidgbob** [comment]
That works! Although am still getting a red warning:

![image](https://github.com/TrailingStop/TT-Miner-release/assets/6987090/06dfe703-b864-46f1-80d8-249f2c2b5c50)

**Comment by TrailingStop** [comment]
if all gpus gets the same value you can just write:
-oc-memlock 810

**Comment by bidgbob** [comment]
All issues solved! Thanks for the help!

### **EXAMPLE BELOW**

For anyone looking to create a flight sheet with multiple GPUs here's an example of a working OC template:

As stated by TrailingStop at the moment the power limits are unnecessary as the power is limited by the core and memory lock!

![image](https://github.com/TrailingStop/TT-Miner-release/assets/6987090/437a1402-66be-4c16-baa2-8a7d70e71d53)
