### ISSUE TITLE
Hiveos custom package command line for triple mining not working

### ISSUE THREAD

**Issue by DmClll** [TrailingStop/TT-Miner-release#38]
Greetings boss, 

Can u please write the command line that will be added to hiveos custom package in order to triple mine ETI/EGAZ/ZIL

Please boss i appreciate your help

**Comment by TrailingStop** [comment]
Hi, please setup hive to mine EGAZ first. The add in custome options:
 -c EGAZ -cETI ETI -PETI <wallet(ETI)>.<worker(ETI)>@<pool-server(ETI)>:<pool-port(ETI)> -cZIL ZIL -PZIL <wallet(ZIL)>.<worker(ZIL)>@<pool-server(ZIL)>:<pool-port(ZIL)> -jETI DEF

**Comment by DmClll** [comment]
Its working boss i love u, Can u please advise how to adjust the hashrate percentage between EGAZ and ETI ?

**Comment by TrailingStop** [comment]
Hi- sure. append a value from -100 to 100 to give the one or the other more gpu power:

sample
-jETI DEF -50
default:
-jETI DEF 0 -> same as just -jETI DEF

**Comment by DmClll** [comment]
Noted with thanks 
Is it possible boss to mine 0xbtc and bnbtc along with ETI ?
How can i achieve that ?

**Comment by TrailingStop** [comment]
Hi - I never tried that, but you can give it a shoot. assume you main coin is ETI:

add -jcoin1 DEF and -jcoin2 DEF

But I'm not sure if that works - never tried it.
