### ISSUE TITLE
How to add it to hiveos?

### ISSUE THREAD

**Issue by kvuseg** [TrailingStop/TT-Miner-release#4]
how to add it to hiveos? it does not work through custom and when replacing it also gives a kernel error

**Comment by TrailingStop** [comment]
Please try again with 2023.1.1. I made two modifications to get it working together with Hive-OS.

**Comment by Mike454545** [comment]
Tried installing it with hive custom miner with new version TT-Miner-2023.1.1.tar.gz
i get No TT-Miner/h-manifest.conf
then just stops.

**Comment by kvuseg** [comment]
yes, same thing. and if you just replace the old miner with a new one, then errors come out or the map settings completely disappear

**Comment by TrailingStop** [comment]
Yes, the archive does not contain the scrips needed by hive. I work to get them included.

**Comment by TrailingStop** [comment]
Hi - I made a hive package. If you like you can give it a try:
https://TradeProject.de/download/Miner/TT-Miner-2023.1.2.Hive.tar.gz

**Comment by Mike454545** [comment]
yep it's working now. only thing big i noticed it's not reporting hash rate to hive os but loging into miner shows it's hashing. dont seem to be going to hive os over clocks either. looks like all gpus are unlocked to full power.

**Comment by TrailingStop** [comment]
Hi- yes, update is comming1

**Comment by TrailingStop** [comment]
Hi - if you want to give give this one a try. It should now show statistics and also taker care of hive core/pl settings if you do not set anything in TT:
https://TradeProject.de/download/Miner/TT-Miner-2023.1.2.Hive.tar.gz

**Comment by Mike454545** [comment]
just tried it, it appears to be exact same no hash rate in hive and over clocks not being set there all going to full power.
07:38:57 GPU[00-DEF]:   1.540 GH/s [A23:R0:S0 0.0%]  CClk:1.957 GHz  MClk:2.205 GHz  50°C  34%  136 W  11.33 MH/s/W  11.65 GB left  last: 0:05                                                                     
07:38:57 GPU[01-DEF]:   1.544 GH/s [A19:R0:S0 0.0%]  CClk:1.972 GHz  MClk:2.205 GHz  52°C  32%  142 W  10.87 MH/s/W  11.65 GB left  last: 0:08                                                                     
07:38:57 GPU[02-DEF]:   1.554 GH/s [A19:R0:S0 0.0%]  CClk:1.972 GHz  MClk:2.205 GHz  43°C  32%  138 W  11.26 MH/s/W  11.65 GB left  last: 0:02                                                                     
07:38:57 GPU[03-DEF]:   2.081 GH/s [A25:R0:S0 0.0%]  CClk:1.965 GHz  MClk:1.705 GHz  55°C  59%  184 W  11.31 MH/s/W  7.645 GB left  last: 0:05                                                                     
07:38:57 GPU[04-DEF]:   1.582 GH/s [A22:R0:S0 0.0%]  CClk:2.017 GHz  MClk:2.205 GHz  53°C  0%  129 W  12.26 MH/s/W  11.65 GB left  last: 0:11                                                                      
07:38:57 GPU[05-DEF]:   2.504 GH/s [A37:R0:S0 0.0%]  CClk:1.935 GHz  MClk:1.705 GHz  55°C  48%  212 W  11.81 MH/s/W  7.624 GB left  last: 0:01                                                                     
07:38:57 GPU[06-DEF]:   1.532 GH/s [A19:R0:S0 0.0%]  CClk:1.950 GHz  MClk:2.205 GHz  53°C  48%  128 W  11.97 MH/s/W  11.65 GB left  last: 0:01                                                                     
07:38:57 GPU[07-DEF]:   1.583 GH/s [A22:R0:S0 0.0%]  CClk:2.010 GHz  MClk:2.205 GHz  54°C  44%  144 W  10.99 MH/s/W  11.65 GB left  last: 0:12

**Comment by TrailingStop** [comment]
Hi, can you please check if the miner files are dated from today?

**Comment by TrailingStop** [comment]
sorry - same version number since it was not really released.

**Comment by Mike454545** [comment]
you uploading a new one then?

**Comment by Mike454545** [comment]
The date on it is from the 15th and today is the 16th so is it not right?

**Comment by Mike454545** [comment]
could you just rename the file just a little bit maybe it's see's it as same link so it's not downloading it?

**Comment by TrailingStop** [comment]
sure - one sec.

**Comment by TrailingStop** [comment]
https://TradeProject.de/download/Miner/TT-Miner-2023.1.3.Hive.tar.gz - but this is just the filename - still version 2023.1.2

**Comment by Mike454545** [comment]
files doesnt exist it says

**Comment by TrailingStop** [comment]
Please try again

**Comment by Mike454545** [comment]
i have no problem getting it to work it just the link you just posted dont exist
https://tradeproject.de/download/Miner/TT-Miner-2023.1.3.Hive.tar.gz

**Comment by TrailingStop** [comment]
oh- sorry, just see that i have a typo. please try again.

**Comment by TrailingStop** [comment]
See the problem. Please try new release - change filename again for you:
TT-Miner-2023.1.4.Hive.tar.gz

**Comment by Mike454545** [comment]
still getting it
![image](https://user-images.githubusercontent.com/73655283/212690300-9603dbe3-4d0c-4895-953e-838743c5eb32.png)

**Comment by TrailingStop** [comment]
newline after algo......one sec.

**Comment by TrailingStop** [comment]
OK - file: TT-Miner-2023.1.5.Hive.tar.gz

**Comment by Mike454545** [comment]
yep looks like it's working the only complaint i have now is it's not reporting hash rate to hive.
![image](https://user-images.githubusercontent.com/73655283/212691594-ae436a15-9db6-43aa-bc98-455e31ee6bc2.png)

**Comment by TrailingStop** [comment]
do you see shares from mining?

**Comment by Mike454545** [comment]
o yeah working good. only thing i have found you can type in on hive a manual command to set core clocks it dont like when you type in nvtool --setcoreoffset 350 it dont mind using this nvtool --setmem 810 --setclocks 1470 but soon as you enter setcoreoffset 350 dont like it.
![image](https://user-images.githubusercontent.com/73655283/212692518-9cbc7f06-6ad1-4ed4-8f21-0d26576084c6.png)

**Comment by TrailingStop** [comment]
you can use TT settings until i have a fix for that:
-oc-core 1470 (all gpus the same rate)
-oc-mem 810

**Comment by Mike454545** [comment]
what about setcoreoffset or dont your miner have that option that command really gets the power down.

**Comment by TrailingStop** [comment]
sorry. so far no offset, but you can set powerlimit with:
-oc-pl 80 -> 80%

**Comment by Mike454545** [comment]
is that something that might be coming? thanks for the help

**Comment by TrailingStop** [comment]
Yes- I already have some requests fore that.
