### ISSUE TITLE
SOLO mining to SATOX QT wallet not working

### ISSUE THREAD

**Issue by captkoksock** [TrailingStop/TT-Miner-release#40]
I've been having issues connecting TT Miner to the Satox wallet for about an hour now

**Comment by TrailingStop** [comment]
Hi, thanks for the report,  I'll check the problem.

**Comment by captkoksock** [comment]
> Hi, thanks for the report, I'll check the problem.

No problem, thanks for the response back. We're you able to figure out a solution? Do you need me to post logs?
