### ISSUE TITLE
No hashrate until first share has been accepted

### ISSUE THREAD

**Issue by RainbowMiner** [TrailingStop/TT-Miner-release#41]
I understand the idea behind that, but it makes running TT-Miner with RainbowMiner very difficult. Sometimes the miner has to run on pools with very high difficulty (e.g. on MiningRigRentals). Then it would take long to find the first share - RainbowMiner will kill TT-Miner, if this should take too long.
Would it be possible, to show the hashrate in the API, even if the miner hasn't found a share yet?

**Comment by TrailingStop** [comment]
Can you please clarify? I'm not sure if I understand correctly. I think TT send the hashrate, even if there was no share - if not it is a bug....

**Comment by RainbowMiner** [comment]
miner_getstat1 - but I also see 0 H/s in the console until the first share has been accepted. This happens with all algorithm.

**Comment by TrailingStop** [comment]
ok. must be a bug. give me some minutes.

**Comment by TrailingStop** [comment]
Maybe I do not get your point?

**Comment by RainbowMiner** [comment]
I will retry KawPow on MiningRigRentals and try to get a log.

**Comment by TrailingStop** [comment]
Hi- just want to catch up? any success with the log?

**Comment by RainbowMiner** [comment]
Unfortunately not - all my rigs got rented out yesterday. Will have to wait until afternoon.

**Comment by RainbowMiner** [comment]
Ok, I did not get back to the above error. 

But instead, this time it is on KawPow / MiningRigRentals:
```
14:41:50.254 Pool[DEF-0]:   -*** Summary for: AlgoDefined / KawPoW
14:41:50.254 GPU[00-DEF]:   -0 H/s [A0:R0:S0 0.0%]  CClk:139.0 MHz-0%  MClk:405.0 MHz-0%  35°C  0%  5 W  0 H/s/W  7.727 GB   -
14:41:50.254 GPU[01-DEF]:   -0 H/s [A0:R0:S0 0.0%]  CClk:139.0 MHz-0%  MClk:405.0 MHz-0%  41°C  0%  5 W  0 H/s/W  7.727 GB   -
14:41:50.254 GPU[02-DEF]:   -0 H/s [A0:R0:S0 0.0%]  CClk:139.0 MHz-0%  MClk:405.0 MHz-0%  44°C  0%  5 W  0 H/s/W  7.727 GB   -
14:41:50.254 GPU[03-DEF]:   -0 H/s [A0:R0:S0 0.0%]  CClk:139.0 MHz-0%  MClk:405.0 MHz-0%  31°C  0%  6 W  0 H/s/W  7.727 GB   -
14:41:50.254 GPU[04-DEF]:   -0 H/s [A0:R0:S0 0.0%]  CClk:139.0 MHz-0%  MClk:405.0 MHz-0%  42°C  0%  4 W  0 H/s/W  7.727 GB   -
14:41:50.254 GPU[05-DEF]:   -0 H/s [A0:R0:S0 0.0%]  CClk:139.0 MHz-0%  MClk:405.0 MHz-0%  40°C  0%  5 W  0 H/s/W  7.727 GB   -
14:41:50.254 All[DEF]:      -0 H/s [A0:R0:S0 0.0%]  30 W  0 H/s/W  uptime: 0 00:00:45  mining-time: 0 00:00:00  last: 00:00
14:41:50.348 Pool[DEF-0]:   -Connected to stratum+tcp://eu-01.miningrigrentals.com:51810 [188.166.37.58].
14:42:03.621 Pool[DEF-0]:   -End of file [asio.misc:2 at W:\3rdParty\boost_1_83_0\boost\asio\detail\win_iocp_socket_recv_op.hpp:90:5 in function 'do_complete'] - func:3
14:42:03.621 Pool[DEF-0]:   -Retry #3 to connect in 15 seconds.
```

**Comment by TrailingStop** [comment]
Hi, looks you get directly disconnected. Do you use the correct protocool? stratum vs stratum1? If you can share your commandline (DM if you want) I can check here. Please also reload the latest 2024.1.2. I just released it with some other fixed some hours ago.

**Comment by RainbowMiner** [comment]
> Please also reload the latest 2024.1.2. I just released it with some other fixed some hours ago.

Yes, it is already the new version :)

> Hi, looks you get directly disconnected. Do you use the correct protocool? stratum vs stratum1?

Yes, it is the correct protocol. Don't mind that problem - all miners seem to have problems to connect to that rental, currently. Most probably the renter has setup an invalid pool.
