### ISSUE TITLE
How to mine zkBTC?

### ISSUE THREAD

**Issue by Fay325** [TrailingStop/TT-Miner-release#42]
not have solo bat.

**Comment by Fay325** [comment]
maybe not  the same coin.  
https://zkbitcoin.org

**Comment by TrailingStop** [comment]
did you try?

**Comment by Fay325** [comment]
![Uploading QQ截图20240321202935.png…]()
![QQ截图20240321203132](https://github.com/TrailingStop/TT-Miner-release/assets/55188181/838ccb0c-903d-4a2d-85d6-2e84b6fe42e9)

**Comment by TrailingStop** [comment]
Please check the new version with auto-protocol selection for zkBTC

**Comment by totosugito** [comment]
> Hi,
> 
> sorry - I do not have the skBTC node. Please try this command:
> 
> tt-miner -c skbtc -P http://<user>:<password>@<node-ip>:<node-port>
> 
> or: tt-miner -a Sha3Solidity -P http://<user>:<password>@<node-ip>:<node-port>
> 
> please let me know if that works.

The command running well. The program send share to the pool too. But, the dashboard miner show empty data (I have checked mining for 30 minutes). My pool is : http://pool.zkBitcoin.org:6122

Thank you

**Comment by totosugito** [comment]
No, I am try to mining to pool : http://pool.zkbitcoin.org/

**Comment by TrailingStop** [comment]
Hi - the pools does not have a DNS entry - so you need to use the IP instead:

24.107.1.190:6122

**Comment by Untouchable2k** [comment]
Please use the new IP for the Pool and Not the DNS entry

97.87.187.33
Port: 6122
