### ISSUE TITLE
mewc 挖掘 拒绝率%100如何解决 我使用的是 HIVE OS 系统

### ISSUE THREAD

**Issue by paopao-tang** [TrailingStop/TT-Miner-release#43]
HIVE OS配置 TT miner  挖掘 mewc 新算法 拒绝率%100
![s2](https://github.com/TrailingStop/TT-Miner-release/assets/98439879/8472a908-d75a-47d4-8de2-967c64db3dc4)
![s2](https://github.com/TrailingStop/TT-Miner-release/assets/98439879/4ead485b-8ed8-44df-98ef-1c340d00f922)
![s1](https://github.com/TrailingStop/TT-Miner-release/assets/98439879/ad2b5368-ca7d-440c-a195-f977f44de208)

**Comment by TrailingStop** [comment]
Hi - please use the latest version 1.8. I think it fixes the bug you see.

**Comment by paopao-tang** [comment]
hive os 还有没升级到 1.8的选项 最多到 1.7

**Comment by TrailingStop** [comment]
You need to add it as custom miner

**Comment by TrailingStop** [comment]
Hi - is it working now?
