### ISSUE TITLE
GPU Memory issue

### ISSUE THREAD

**Issue by BartManX** [TrailingStop/TT-Miner-release#45]
15:56:29.815 ********* TT-Miner - Version: 2024.2.0 (Apr 20 2024 20:06:37)
15:56:29.815 ********* Log system initialized...
15:56:29.815 ********* Internal event system initialized...
15:56:29.815 ********* Worker threads initialized, using 64 threads...
15:56:29.824 ********* Commandline: ./TT-Miner -a meowpow -P MSciTiL9AbKAE1uBuf8uPGXbPyaVut7RMx.3x3060:x@us-east.miningcrypto.online:8881
15:56:30.320 Krnl[00]:      Create CUDA-Kernel configuration (CU_G-D003#0-86) for compute 8.6
15:56:30.320 ********* CUDA-GPU information
15:56:30.321 GeForce Driver-Ver:       535.171.4
15:56:30.321 CUDA-Ver:                 12.2
15:56:30.321 NVML-Ver:                 12.535.171-4
15:56:30.321 NVRTC-Ver:                12.4
15:56:30.321
15:56:30.321       CUDA devices:       3
15:56:30.321 * #00 PCI 41:00.0 Zotac   NVIDIA GeForce RTX 3060  12.00 GB / 2.485 GB  SM/Cores: 28/3584   {845E10CD-DE08-4E4D-3119-EAEF0F8F3A0B}
15:56:30.321                           Supported MemClk lock(-oc-mem): 405, 810, 5001, 7301, 7501
15:56:30.321 * #01 PCI 61:00.0 Zotac   NVIDIA GeForce RTX 3060  12.00 GB / 2.485 GB  SM/Cores: 28/3584   {E952BDE7-9648-0612-2474-9D2A896DB720}
15:56:30.321                           Supported MemClk lock(-oc-mem): 405, 810, 5001, 7301, 7501
15:56:30.321 * #02 PCI 62:00.0 Zotac   NVIDIA GeForce RTX 3060  12.00 GB / 2.485 GB  SM/Cores: 28/3584   {84095E16-D64C-5222-3583-D2A10DA9B977}
15:56:30.321                           Supported MemClk lock(-oc-mem): 405, 810, 5001, 7301, 7501
15:56:30.321
15:56:30.321
15:56:30.321 Algo-1 "DEF"-Regular:     from command line option
15:56:30.321              -Selector:   DEF
15:56:30.321              -Algo:       MeowPoW - AlgoFamily: PROGPOW
15:56:30.321              -Coin:       MeowCoin (MEWC)
15:56:30.321              -SelDev:     0 1 2
15:56:30.321 Primary server:           us-east.miningcrypto.online:8881 - SocketStratum
15:56:30.321              -Wallet:     MSciTiL9AbKAE1uBuf8uPGXbPyaVut7RMx
15:56:30.321              -Worker:     3x3060
15:56:30.321              -Pwd:        x
15:56:30.321
15:56:30.321 ********* Hash speed reporting
15:56:30.321 Avg. performance time frame:      2 minutes
15:56:30.321 Performance summary(sec.):        30 seconds
15:56:30.321 Performance summary(shares):      disabled
15:56:30.321
15:56:30.321 ********* Apply settings
15:56:30.321 Temp control:                     disabled
15:56:30.322 API-Interface:                    disabled
15:56:30.322 Broadcast hashrate:               enabled
15:56:30.322
15:56:30.322 ***
15:56:30.322
15:56:30.322
15:56:30.322  _______ _______     __  __ _____ _   _ ______ _____
15:56:30.322 |__   __|__   __|   |  \/  |_   _| \ | |  ____|  __ \
15:56:30.322    | |     | |______| \  / | | | |  \| | |__  | |__) |
15:56:30.322    | |     | |______| |\/| | | | | . ` |  __| |  _  /
15:56:30.322    | |     | |      | |  | |_| |_| |\  | |____| | \ \
15:56:30.322    |_|     |_|      |_|  |_|_____|_| \_|______|_|  \_\
15:56:30.322
15:56:30.322
15:56:30.322 ***
15:56:30.322 Version: TT-Miner (2024.2.0 Apr 20 2024)
15:56:30.322 Get 20% discount on your Binance Exchange trading fees and support TT-Miner
15:56:30.322   TT  / You          link
15:56:30.322  20%     0%          https://accounts.binance.com/en/register?ref=28122598
15:56:30.322  15%     5%          https://accounts.binance.com/en/register?ref=UJPASPV6
15:56:30.322  10%    10%          https://accounts.binance.com/en/register?ref=LAUV5U9I
15:56:30.322 ***
15:56:30.322
15:56:30.322 ********* Press 'x' to enter menu
15:56:30.322
15:56:30.322 ********* Selected Devices - overview
15:56:30.322 * #00 PCI 41:00.0 Zotac   NVIDIA GeForce RTX 3060
15:56:30.322 * #01 PCI 61:00.0 Zotac   NVIDIA GeForce RTX 3060
15:56:30.322 * #02 PCI 62:00.0 Zotac   NVIDIA GeForce RTX 3060
15:56:30.322
15:56:30.322
15:56:30.322 ********* DevFee: 1.00%
15:56:30.322
15:56:30.322 ********* Start mining
15:56:30.322
15:56:30.479 Pool[MEWC-0]:  -Connected to stratum+tcp://us-east.miningcrypto.online:8881 [15.204.248.242].
15:56:30.521 Pool[MEWC-0]:  *Set pool extra nonce to: 0x608
15:56:30.556 Pool[MEWC-0]:  *Difficulty set to 431.2 MH
15:56:30.556 Coin[MEWC]:    *Switch to DAG for epoch 452
15:56:30.556 Pool[MEWC-0]:  *Received new job#: 3f1
15:56:30.556 Pool[MEWC-0]:  *Working on Block#: 851454 - Blocks until epoch change: 3546
15:56:30.556 Coin[MEWC]:    *Modify algo for block: 851454, ProgPoW period: 141909
15:56:30.563 Dag[02-MEWC]:  *DAG(D452-52) requested - size: 4.531 GB
15:56:30.563 Dag[01-MEWC]:  *DAG(D452-52) requested - size: 4.531 GB
15:56:30.563 Dag[00-MEWC]:  *DAG(D452-52) requested - size: 4.531 GB
15:56:30.716 Pool[MEWC-0]:  *Received new job#: 3f1
15:56:31.079 Krnl[00]:      CUDA-Kernel configuration ready (CU_G-D003#0-86). (0.7 secs)
15:56:31.079 Krnl[00-MEWC]: *Create CUDA-Kernel configuration (CU_G-A052#6EDD-86) for compute 8.6
15:56:34.679 Krnl[00-MEWC]: *CUDA-Kernel configuration ready (CU_G-A052#6EDD-86). (3.5 secs)
15:56:34.679 Krnl[02-MEWC]: *Create CUDA-Kernel configuration (CU_G-A052#6EDE-86) for compute 8.6
15:56:38.853 Pool[MEWC-0]:  *Received new job#: 3f2
15:56:38.853 Pool[MEWC-0]:  *Working on Block#: 851455 - Blocks until epoch change: 3545
15:56:39.245 Krnl[02-MEWC]: *CUDA-Kernel configuration ready (CU_G-A052#6EDE-86). (4.5 secs)
15:57:00.328 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:57:00.328 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:57:00.328 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:57:00.328 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:57:00.328 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:00:30  mining-time: 0 00:00:29  last: 00:00
15:57:11.876 Pool[MEWC-0]:  *Received new job#: 3f3
15:57:11.876 Pool[MEWC-0]:  *Working on Block#: 851456 - Blocks until epoch change: 3544
15:57:30.327 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:57:30.327 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:57:30.327 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:57:30.327 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:57:30.327 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:01:00  mining-time: 0 00:00:59  last: 00:00
15:58:00.327 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:58:00.327 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:58:00.327 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:58:00.327 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:58:00.327 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:01:30  mining-time: 0 00:01:29  last: 00:00
15:58:12.045 Pool[MEWC-0]:  *Received new job#: 3f4
15:58:30.328 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:58:30.328 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:58:30.328 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:58:30.328 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:58:30.328 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:02:00  mining-time: 0 00:01:59  last: 00:00
15:58:36.925 Pool[MEWC-0]:  *Received new job#: 3f5
15:58:36.925 Pool[MEWC-0]:  *Working on Block#: 851457 - Blocks until epoch change: 3543
15:59:00.327 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:59:00.327 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:00.327 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:00.327 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:00.327 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:02:30  mining-time: 0 00:02:29  last: 00:00
15:59:01.928 Pool[MEWC-0]:  *Received new job#: 3f6
15:59:01.928 Pool[MEWC-0]:  *Working on Block#: 851458 - Blocks until epoch change: 3542
s15:59:21.412 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:59:21.412 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:21.412 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:21.412 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:21.412 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:02:51  mining-time: 0 00:02:50  last: 00:00
s15:59:24.920 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:59:24.920 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:24.920 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:24.920 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:24.920 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:02:54  mining-time: 0 00:02:54  last: 00:00
d15:59:27.922 GPU[00]:       DAG-Information for: NVIDIA GeForce RTX 3060
15:59:27.922 GPU[01]:       DAG-Information for: NVIDIA GeForce RTX 3060
15:59:27.922 GPU[02]:       DAG-Information for: NVIDIA GeForce RTX 3060
15:59:30.333 Pool[MEWC-0]:  **** Summary for: MeowCoin / MeowPoW
15:59:30.333 GPU[00-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:30.333 GPU[01-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:30.333 GPU[02-MEWC]:  **Standby - not enough GPU memory to run 'MeowPoW'
15:59:30.333 All[MEWC]:     *0 H/s [A0:R0:S0 0.0%]  uptime: 0 00:03:00  mining-time: 0 00:02:59  last: 00:00

**Comment by TrailingStop** [comment]
Hi,

for some reason your GPUs have just 2.5GB free memory:
 #00 PCI 41:00.0 Zotac NVIDIA GeForce RTX 3060 12.00 GB / 2.485 GB

MeowPow requires more than 4GB - so that will not fit.

**Comment by TrailingStop** [comment]
Hi - is it working now? Any other bug or issue I can help with?
