### ISSUE TITLE
Where is the API ?!

### ISSUE THREAD

**Issue by Mini-Digger** [TrailingStop/TT-Miner-release#46]
Your program does not provide an API? Other kernels are available, so you probably don't lack this technology. I hope to improve this basic function as soon as possible!

**Comment by TrailingStop** [comment]
just add -b (like for any other miner) and the API is enabled.

**Comment by Mini-Digger** [comment]
-b 127.0.0.1:8888
Is it ok?

**Comment by Mini-Digger** [comment]
Gminer：--api - telemetry server port, allows you to monitor the miner status remotely, open a link in your browser http://localhost:port/ (for example: '10050', '20030')
Rigel：--api-bind <IP:PORT>
          Enables HTTP API and binds it to the specified socket address
And u？

**Comment by TrailingStop** [comment]
same

**Comment by Mini-Digger** [comment]
Get

**Comment by Mini-Digger** [comment]
What is the url of json?

**Comment by TrailingStop** [comment]
default is: 127.0.0.1:4068

**Comment by Mini-Digger** [comment]
I need json data

**Comment by TrailingStop** [comment]
what data do you need? TT replies on standard request on any ip:port you like

**Comment by Mini-Digger** [comment]
For example,the given URL is 127.0.0.1:4068/stat
After opening, the content will display something similar to the following:
{
    "miner": "GMiner 3.44",
    "uptime": 34,
    "server": "ergo.666pool.com:9556",
    "user": "okczb1234.112",
    "extended_share_info": true,
    "shares_per_minute": 0,
    "pool_speed": 0,
    "algorithm": "Autolykos2",
    "electricity": 0.001,
    "total_accepted_shares": 0,
    "total_rejected_shares": 0,
    "total_stale_shares": 0,
    "total_invalid_shares": 0,
    "devices": [
        {
            "gpu_id": 0,
            "bus_id": "0000:01:00.0",
            "name": "3060Ti",
            "speed": 145745156,
            "accepted_shares": 0,
            "rejected_shares": 0,
            "stale_shares": 0,
            "invalid_shares": 0,
            "fan": 85,
            "temperature": 44,
            "temperature_limit": 90,
            "memory_temperature": 0,
            "memory_temperature_limit": 120,
            "core_clock": 1470,
            "memory_clock": 7550,
            "power_usage": 119
        }
    ],
    "speed_rate_precision": 0,
    "speed_unit": "H/s",
    "power_unit": "H/W"
}

**Comment by Mini-Digger** [comment]
Provide at least one hash value, such as
{
"Total - all Devices“:" 572 H/s"
}

**Comment by Mini-Digger** [comment]
Facilitating the use of TT with my mining UI software

**Comment by TrailingStop** [comment]
just send the request to the port. You can have 3 different levels of information:
{"id":1,"jsonrpc":"2.0","method":"miner_getstat1"}
{"id":1,"jsonrpc":"2.0","method":"miner_getstat2"}
{"id":1,"jsonrpc":"2.0","method":"miner_getstatdetail"}

TT will then reply with the information level you request. Can you send data?

**Comment by Mini-Digger** [comment]
It should work, I'll give it a try first. If it doesn't work, I'll ask you for advice

**Comment by TrailingStop** [comment]
sure - please do not forget to ad a newline after the json!

**Comment by Mini-Digger** [comment]
It works！THX

**Comment by TrailingStop** [comment]
happy to help
