### ISSUE TITLE
v2024.2.0 (Windows): Device order incorrect?

### ISSUE THREAD

**Issue by UselessGuru** [TrailingStop/TT-Miner-release#47]
Devices are incorrectly sorted:

```
22:47:22.538   #00 PCI 01:00.0 MSI                            NVIDIA GeForce GTX 1660 SUPER
22:47:22.538   #01 PCI 0C:00.0 ASUS                           NVIDIA GeForce GT 1030
22:47:22.538   #02 PCI 10:00.0 Gainward                       NVIDIA GeForce GTX 750 Ti
22:47:22.538   #03 PCI 07:00.0 Advanced Micro Devices, Inc.   Radeon RX 580 Series
22:47:22.538 * #04 PCI 0B:00.0 Advanced Micro Devices, Inc.   AMD Radeon RX 5700 XT
```

With '-cuda-order' the order remains the same:

```
22:52:56.717   #00 PCI 01:00.0 MSI                            NVIDIA GeForce GTX 1660 SUPER
22:52:56.717   #01 PCI 0C:00.0 ASUS                           NVIDIA GeForce GT 1030
22:52:56.717   #02 PCI 10:00.0 Gainward                       NVIDIA GeForce GTX 750 Ti
22:52:56.717   #03 PCI 07:00.0 Advanced Micro Devices, Inc.   Radeon RX 580 Series
22:52:56.717 * #04 PCI 0B:00.0 Advanced Micro Devices, Inc.   AMD Radeon RX 5700 XT
```

I would expect that by default (without '-cuda-order') the devices should be sorted like this:

```
GPU0: MSI NVIDIA GeForce GTX 1660 SUPER 6GB  PCI: 0000:01:00.0
GPU1: MSI Radeon RX 580 Series 8GB           PCI: 0000:07:00.0
GPU2: GIGABYTE AMD Radeon RX 5700 XT 8GB     PCI: 0000:0b:00.0
GPU3: ASUS NVIDIA GeForce GT 1030 2GB        PCI: 0000:0c:00.0
GPU4: GAINWARD NVIDIA GeForce GTX 750 Ti 2GB PCI: 0000:10:00.0
```

**Comment by UselessGuru** [comment]
Any plans to change this?

**Comment by TrailingStop** [comment]
Hi - I already looks into this. Problem is the mixed opencl/cuda devices. cuda order is in most cases also a performance order, but the opencl devices are not included. so they have a 'special' role in the list. I will see what I can do, but most likely I will append the opencl devices to the list of cuda devices.

**Comment by UselessGuru** [comment]
> order by pci will be fixed

That would be fine for me.

**Comment by RainbowMiner** [comment]
Is the device order now like
```
22:52:56.717   #00 PCI 01:00.0 MSI                            NVIDIA GeForce GTX 1660 SUPER
22:52:56.717   #01 PCI 0C:00.0 ASUS                           NVIDIA GeForce GT 1030
22:52:56.717   #02 PCI 10:00.0 Gainward                       NVIDIA GeForce GTX 750 Ti
22:52:56.717   #03 PCI 07:00.0 Advanced Micro Devices, Inc.   Radeon RX 580 Series
22:52:56.717 * #04 PCI 0B:00.0 Advanced Micro Devices, Inc.   AMD Radeon RX 5700 XT
```
.. say, you simply add OpenCL devices at the end of the CUDA devices list

or is it now like
```
GPU0: MSI NVIDIA GeForce GTX 1660 SUPER 6GB  PCI: 0000:01:00.0
GPU1: MSI Radeon RX 580 Series 8GB           PCI: 0000:07:00.0
GPU2: GIGABYTE AMD Radeon RX 5700 XT 8GB     PCI: 0000:0b:00.0
GPU3: ASUS NVIDIA GeForce GT 1030 2GB        PCI: 0000:0c:00.0
GPU4: GAINWARD NVIDIA GeForce GTX 750 Ti 2GB PCI: 0000:10:00.0
```
.. say, ordered by PCI only, no matter if it is an OpenCL or a CUDA device
?

**Comment by TrailingStop** [comment]
hi. default is by pci bus.

**Comment by RainbowMiner** [comment]
Ok, so it is the second. Thank you for the answer!

Another question: what about the iGPU. I noticed, that it is listed after my other GPUs, even though it comes at PCI "00:02" - I would have expected it to be listed as index 0. For example on my notebook:

```
12:52:12.763       CUDA devices:       1
12:52:12.763 * #00 PCI 01:00.0 ASUS   NVIDIA GeForce RTX 3060 Laptop GPU  6.000 GB / 4.593 GB  SM/Cores: 30/3840  8.6  {B3406A7D-1C56-8C06-2092-5743B0853295}
12:52:12.763                          Supported MemClk lock(-oc-mem): 405, 810, 5501, 6001
12:52:12.763
12:52:12.763
12:52:12.764 ********* OpenCl-Devices(iGPU) information
12:52:12.764       iGPU devices:       1
12:52:12.764 * #01 PCI 00:02.0         Intel(R) Iris(R) Xe Graphics  12.68 GB / 0 B       SM: 96   1.2
```

**Comment by TrailingStop** [comment]
OK- there are lists of gpus on some places in the miner. At program start TT lists the devices by 'category'. First cpus, then cuda and last is opencl. Before starting a short list with all devices and a remark if used or not is printed: like this - independent of the category, sorted by PCI:
10:30:29.075 * #05 PCI 00:00.0 GenuineIntel           Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 8 Cores, 16 Threads
10:30:29.075   #03 PCI 00:00.0 Intel(R) Corporation   Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 16 Threads (OpenCL)
10:30:29.075   #04 PCI 00:02.0 Intel(R) Corporation   Intel(R) UHD Graphics 630
10:30:29.076   #00 PCI 01:00.0 ASUS                   NVIDIA GeForce GTX 1050 Ti
10:30:29.076   #01 PCI 02:00.0 Zotac                  NVIDIA GeForce RTX 3060
10:30:29.076   #02 PCI 07:00.0 MSI                    NVIDIA GeForce GTX 1070

Here you see that only the cpu (id #05)is used. 

and this is also the order the devices are used in the status print.

**Comment by RainbowMiner** [comment]
Looking at your example, are the devices now addressed with the "#1", "#2".. id number (-d 5 would address the CPU) or is the real sorting being used (-d 0 would address the CPU).

**Comment by TrailingStop** [comment]
no- you are correct. -d uses the id.

**Comment by RainbowMiner** [comment]
Please correct me, if I am wrong:
So the following is correct for the `-d <id>` (`#<id>`). Device `#<id>` is the numbers you get, when you sort all devices by category (1. CUDA, 2. OpenCL, 3. CPU) and then each group by PCI bus id.

**Comment by TrailingStop** [comment]
the numbers (id) should be always the same - no matter how you sort the devices, by category or PCI.

**Comment by RainbowMiner** [comment]
It is important for me, that I am able to select each device exactly without having to use the `tt-miner -l` list command. That means, I need to know the numbers for the `-d` parameter.

Take the following example. To address the CPU, I need `-d 8`, for the iGPU, i would need `-d 7` and for the RTX3070 a `-d 6` would be the right choice. Correct?

```
13:43:20.634 ********* Commandline: .\tt-miner -l
13:43:22.327 ********* CPU/Core information
13:43:22.329       CPU/Core devices:   1
13:43:22.330 * #08                     GenuineIntel Intel(R) Pentium(R) CPU G4560 @ 3.50GHz   2 Cores, 4 Threads
13:43:22.333                           Cache: L1(Data): 32.77 kB, L1(Code): 32.77 kB, L2: 262.1 kB, L3: 3.146 MB/4 Threads, 786.4 kB/per Thread
13:43:22.334                           Extensions: SSE AES
13:43:22.334
13:43:22.335
13:43:22.336 ********* CUDA-GPU information
13:43:22.337 GeForce Driver-Ver:       551.86
13:43:22.338 CUDA-Ver:                 12.4
13:43:22.338 NVML-Ver:                 12.551.86
13:43:22.339 NVRTC-Ver:                12.4
13:43:22.340
13:43:22.340       CUDA devices:       7
13:43:22.341 * #00 PCI 01:00.0 ASUS   NVIDIA GeForce GTX 1070  8.000 GB / 7.745 GB  SM/Cores: 15/1920  6.1  {CCD86D0D-698D-C9B2-4741-4EBFA608C2B5}
13:43:22.341                          Supported MemClk lock(-oc-mem): 405, 810, 3802, 4004
13:43:22.345 * #01 PCI 02:00.0 ASUS   NVIDIA GeForce GTX 1070  8.000 GB / 7.745 GB  SM/Cores: 15/1920  6.1  {FFD82475-22D1-B199-65A8-8AF66E6CE507}
13:43:22.357                          Supported MemClk lock(-oc-mem): 405, 810, 3802, 4004
13:43:22.372 * #02 PCI 03:00.0 ASUS   NVIDIA GeForce GTX 1070  8.000 GB / 7.745 GB  SM/Cores: 15/1920  6.1  {A144C04F-1FBE-CCF9-3B16-58CA3F6135BC}
13:43:22.372                          Supported MemClk lock(-oc-mem): 405, 810, 3802, 4004
13:43:22.375 * #03 PCI 05:00.0 ASUS   NVIDIA GeForce GTX 1070  8.000 GB / 5.133 GB  SM/Cores: 15/1920  6.1  {5D3DE2E4-F459-8FBB-E993-31A79D1C3E87}
13:43:22.376                          Supported MemClk lock(-oc-mem): 405, 810, 3802, 4004
13:43:22.377 * #04 PCI 07:00.0 ASUS   NVIDIA GeForce GTX 1070  8.000 GB / 6.424 GB  SM/Cores: 15/1920  6.1  {62144DAE-B059-032B-799B-77E352F7A299}
13:43:22.378                          Supported MemClk lock(-oc-mem): 405, 810, 3802, 4004
13:43:22.378 * #05 PCI 08:00.0 ASUS   NVIDIA GeForce GTX 1070  8.000 GB / 6.424 GB  SM/Cores: 15/1920  6.1  {82AA27A6-B6C2-CF4F-B7E2-81EA0BBF925B}
13:43:22.379                          Supported MemClk lock(-oc-mem): 405, 810, 3802, 4004
13:43:22.380 * #06 PCI 09:00.0 ASUS   NVIDIA GeForce RTX 3070  8.000 GB / 1.466 GB  SM/Cores: 46/5888  8.6  {BEE9C09E-5BB2-CF86-3D9E-D251029CF127}
13:43:22.380                          Supported MemClk lock(-oc-mem): 405, 810, 5001, 6801, 7001
13:43:22.381
13:43:22.381
13:43:22.382 ********* OpenCl-Devices(iGPU) information
13:43:22.383       iGPU devices:       1
13:43:22.384 * #07 PCI 00:02.0         Intel(R) HD Graphics 610  3.157 GB / 0 B       SM: 12   1.2     {86800000-0259-0000-0000-000000000000}
13:43:22.385
13:43:22.386
```

**Comment by RainbowMiner** [comment]
I think, best for me would be to have a select paramter like `-mode <mode>`, where `<mode>` would be `cuda`, `opencl`, `cpu` and the `-d` device list would for each mode start at index 0 and sorted by PCI bus id.

For the above example `-mode cuda -d 6` would select the RTX3070, `-mode cpu` always only uses the CPU (no -d needed) and `-mode opencl -d 0` would select the iGPU.

**Comment by TrailingStop** [comment]
the most reliable is the pci pus number, but this can be tricky for cpus, but is easy and reliable for gpus. Should I add a 'special' option that switches to 'PCI-IDs'?

**Comment by RainbowMiner** [comment]
> the most reliable is the pci pus number, but this can be tricky for cpus, but is easy and reliable for gpus. Should I add a 'special' option that switches to 'PCI-IDs'?

In fact, possibly using `-d 09:00` or `-d 00:02` would be the most reliable. For CPU, you could simply use `-d cpu` or an extra parameter like `-cpu-only` without the extra need of -d

**Comment by TrailingStop** [comment]
Not completely correct for all systems. I have some miners using dual cpu boards. TT can handle both cpus separat - so you can min with cpu0 spectre and with cpu1 mine xelis.
And how would you activate cuda #0 and amd #0?

**Comment by RainbowMiner** [comment]
> Not completely correct for all systems. I have some miners using dual cpu boards. TT can handle both cpus separat - so you can min with cpu0 spectre and with cpu1 mine xelis. And how would you activate cuda #0 and amd #0?

You are right - dual CPU boards are difficult. So best would be `-d 00:02 0c:00` as addressing.

**Comment by TrailingStop** [comment]
I will add a function that detects the ':' in the values if the -d option. If you use it, TT will treat the values as pci channel and not as id.

**Comment by TrailingStop** [comment]
One question. I guess you find the PCI # yourself, how should we go ahead with cpus? I set them to 0:0:0 and 0:0:1 etc

**Comment by RainbowMiner** [comment]
> I set them to 0:0:0 and 0:0:1

Thats perfect.

**Comment by TrailingStop** [comment]
Hi-

please find a new beta here that includes the first iteration of the new, additional device numbering.

www.TradeProject.de/download/Miner/TT-Miner-2024.3.3b1.Hive.tar.gz
www.TradeProject.de/download/Miner/TT-Miner-2024.3.3b1.tar.gz
www.TradeProject.de/download/Miner/TT-Miner-2024.3.3b1.zip

you can now add the PCI-Bus & device to identify an device like this:

21:38:08.802 ********* Selected Devices - overview
21:38:08.803   #03 PCI 00:00.0 Intel(R) Corporation   Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 16 Threads (OpenCL)
21:38:08.803 * #04 PCI 00:02.0 Intel(R) Corporation   Intel(R) UHD Graphics 630
21:38:08.803   #00 PCI 01:00.0 ASUS                   NVIDIA GeForce GTX 1050 Ti
21:38:08.803 * #01 PCI 02:00.0 Zotac                  NVIDIA GeForce RTX 3060
21:38:08.803 * #02 PCI 07:00.0 MSI                    NVIDIA GeForce GTX 1070
21:38:08.804   #05 PCI ff:00.0 GenuineIntel           Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz 8 Cores, 16 Threads

To select the zotac gpu you can add:
-d 1
or you use the PCI id:
-d 02:00

you can also mix:
-d 02:00,4
to select the internal iGPU of the cpu and the zotac.

Native cpu devices will get an PCI bud number of 0xff and the cpu id as the device number. The first cpu gets ffd:00 to select.

Please let me know if that works OK for you.

**Comment by RainbowMiner** [comment]
The beta works great :) All GPU and CPU can be selected without any problem.

**Comment by TrailingStop** [comment]
cool. thanks for your feedback.

**Comment by RainbowMiner** [comment]
One item on the list: mining on virtual CPUs on Linux do not work. It seems, TTminer cannot detect these CPUs correctly. Says "No devices that can be used for mining selected."
It would be easy to let TTminer run on these CPUs as well. You could use the contents of `/proc/cpuinfo` for detection (lscpu fails on most virtual servers)

**Comment by TrailingStop** [comment]
Hi- I'm not using lscpu, I'm already using the sys fs. I iterate through all the available 'cpus' in /sys/devices/system/cpu. maybe this is not populated fir virtual cpus?

**Comment by RainbowMiner** [comment]
It looks like it is populated:
```
root:/sys/devices/system/cpu# ls -la
insgesamt 0
drwxr-xr-x 55 root root    0 Apr 18 00:23 .
drwxr-xr-x 10 root root    0 Apr 20 04:10 ..
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu0
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu1
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu2
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu3
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu4
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu5
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu6
drwxr-xr-x  9 root root    0 Apr 18 00:23 cpu7
-r--r--r--  1 root root 4096 Aug  8 12:10 kernel_max
-r--r--r--  1 root root 4096 Jul 20 13:16 offline
-r--r--r--  1 root root 4096 Apr 18 00:23 online
-r--r--r--  1 root root 4096 Apr 18 00:24 possible
-r--r--r--  1 root root 4096 Apr 18 05:44 present
```

Is there a special file you are looking for inside the cpuX folders?

**Comment by TrailingStop** [comment]
Hi - can you please switch to the latest beta (5)? Just to make sure we use the same binary.
