### ISSUE TITLE
2023.1.1 (Windows): Out of memory message

### ISSUE THREAD

**Issue by UselessGuru** [TrailingStop/TT-Miner-release#5]
09:46:18 ********* Start API Monitor Listener
09:46:18 ********* Start mining
09:46:18 ********* Mining fee for 'ETHASH': 1.00%
09:46:18 ********* Start worker loop...
09:46:18 Pool[DEF-0]:   Connecting to: stratum+tcp://daggerhashimoto.auto.nicehash.com:9200
09:46:18 Pool[DEF-0]:   Connected to: daggerhashimoto.auto.nicehash.com:9200 - IP4/IP6: 34.149.10.66
09:46:18 Pool[DEF-0]:   Set pool extra nonce to: 0x672C82
09:46:18 Pool[DEF-0]:   Difficulty changed from 0 H to 1.708 GH
09:46:18 Coin[DEF]:     Switch to DAG for epoch 544
09:46:18 Pool[DEF-0]:   Received new job#: 19659f93
09:46:18 Krnl[00-DEF]:  Create Kernel (A032#0-75) for NVIDIA GeForce GTX 1660 SUPER
09:46:18 Dag[00-DEF]:   DAG(D544-32) is too large for this GPU. DAG size: 5.250 GB, **available on GPU: 0 B.**
09:46:18 Miner:         ******** No active GPU left for mining 'ETHASH'. TT-Miner terminates now.

What is the minimum memory requirements for each algo? 
Im this case GTX1660Super is a 6GB card, but the miner reports 0B.

**Comment by TrailingStop** [comment]
Hi,

thanks for the bug report. Do you have a screen attached to that GPU? When TT starts, it prints a status of the GPU before any memory is allocated. That looks like this:
09:29:17 * #0 CudaId-2 PCI 01:00.0 nVidia  NVIDIA GeForce GTX 1050 Ti  4.000 GB / 1.754 GB  SM: 6   Compute: 6.1
09:29:17 * #1 CudaId-0 PCI 02:00.0 nVidia  NVIDIA GeForce RTX 3060     12.00 GB / 11.84 GB  SM: 28  Compute: 8.6
09:29:17 * #2 CudaId-1 PCI 06:00.0 nVidia  NVIDIA GeForce GTX 1070     8.000 GB / 7.892 GB  SM: 15  Compute: 6.1

It shows build in memory and the memory that is available for TT. Can you please send a screenshot from this information?
Thanks a lot.

**Comment by UselessGuru** [comment]
20:00:52 GeForce Driver-Ver:    527.56
20:00:52 Installed CUDA-Ver:    12.0
20:00:52 Supported CUDA-Ver:    11.8
20:00:52 Active CUDA-Ver:       11.8
20:00:52
20:00:52       CUDA devices:    3
20:00:52 * #0 CudaId-0 PCI 11:00.0 nVidia  NVIDIA GeForce GTX 1660 SUPER  6.000 GB / 5.840 GB  SM: 22  Compute: 7.5
20:00:52   #1 CudaId-1 PCI 12:00.0 nVidia  NVIDIA GeForce GT 1030         2.000 GB / 922.7 MB  SM: 3   Compute: 6.1
20:00:52   #2 CudaId-2 PCI 16:00.0 nVidia  NVIDIA GeForce GTX 750 Ti      2.000 GB / 1.426 GB  SM: 5   Compute: 5.0

**Comment by UselessGuru** [comment]
Version 2023.1.6:

23:23:50.468       CUDA devices:    3
23:23:50.473 * #0 CudaId-0 PCI 11:00.0   NVIDIA GeForce GTX 1660 SUPER  6.000 GB / 5.840 GB  SM: 22  Compute: 7.5
23:23:50.473   #1 CudaId-1 PCI 12:00.0   NVIDIA GeForce GT 1030         2.000 GB / 910.2 MB  SM: 3   Compute: 6.1
23:23:50.473   #2 CudaId-2 PCI 16:00.0   NVIDIA GeForce GTX 750 Ti      2.000 GB / 1.959 GB  SM: 5   Compute: 5.0

23:23:50.663 Pool[FIRO-0]:  Connecting to: stratum+tcp://firopow.mine.zergpool.com:3001
23:23:50.720 Pool[FIRO-0]:  Connected to: firopow.mine.zergpool.com:3001 - IP4/IP6: 103.249.70.7
23:23:50.776 Pool[FIRO-0]:  Set pool extra nonce to: 0x84B994
23:23:50.924 Pool[FIRO-0]:  Difficulty changed from 0 H to 42.95 MH
23:23:50.929 Coin[FIRO]:    Switch to DAG for epoch 481
23:23:50.929 Pool[FIRO-0]:  Received new job#: 2200c
23:23:50.929 Pool[FIRO-0]:  Working on Block#: 626093 - Blocks until epoch change: 507
23:23:50.929 Coin[FIRO]:    Modify algo for block: 626093, ProgPoW period: 626093
23:23:50.929 Krnl[00-FIRO]: Create Kernel (A049#1E922-75) for NVIDIA GeForce GTX 1660 SUPER
23:23:50.099 Dag[00-FIRO]:  DAG(D481-49) is too large for this GPU. DAG size: **5.258 GB,** available on GPU: 0 B.
23:23:50.099 Miner:         ******** No active GPU left for mining 'FIRO'. TT-Miner terminates now.

DAG for Firo is only 4.77 GB

**Comment by UselessGuru** [comment]
Still an issue with 2023.1.7

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by TrailingStop** [comment]
Hi - sorry for my late reply. I'm still working on a new version. I think this bug is fixed.

**Comment by UselessGuru** [comment]
> I'm still working on a new version. I think this bug is fixed.

Any idea when you release a new version?

**Comment by TrailingStop** [comment]
Hi - I think this bug is fixed in the new beta - 2023.2.0. At the moment windows only, Linux will follow soon.
