### ISSUE TITLE
Spectrex on on CPU mining suddenly closes on windows after 9 mins and 59 seconds on 2 of my 3 computers

### ISSUE THREAD

**Issue by SomethingGettingWrong** [TrailingStop/TT-Miner-release#50]
So im using the latest TT miner and when I run them at 9 minutes and 59 seconds they just close  on 2 of both of my sonscomputers they mine fine but at 10 mins it just exits. my ohter computer does not do this.. It is a laptop. Runs all day long. 
 
 There is no issue. at 10 mins it exits. i relaunch it.. getting tired of doing it.. while trying to figure out what is causing it. have any ideas? 
 
 Windows 10 on all 3
 
 what happens at 10 mins that would make them exit?
 The only diffrence is the 2 at 10 minutes is updated all the way on the Operating system... the one running longer is fresh install and not updated all the way.. 

im going ot reinstall windows 10 on both pcs' taht are acting wierd tommrow. Logic says it will work until a specific update.. of which breaks it. Although it could be soemthing as simple as latest version of windows defender stops connectivity after 10 mins? does something in  your connection software trigger after 10 mins?

**Comment by TrailingStop** [comment]
Hi, yes, devfee starts after around 10 minutes. Can you please run the miner on the problematic machines with -ccd -log -logpool? That will create logfiles and a crashdump file that might give me more information what causes the crash.

**Comment by SomethingGettingWrong** [comment]
Yes, so sorry its been a few days. So 2 of the computers i completely reformatted windows and installed all updates and same thing.. with or without updates. The other 3 computers i have will not work but this specific one. It just exits it seems. here are the logs all do the same thing at 9 mins 59 seconds.. or at 10 mins. 
[Logs.zip](https://github.com/user-attachments/files/16289439/Logs.zip)

**Comment by TrailingStop** [comment]
Hi- thanks for the logs. You reinstalled windows 10 again or windows 11? How much memory (RAM) do the machines have?

**Comment by SomethingGettingWrong** [comment]
Yes, i reinstaled windows 10 on all 4 machines and updated all the way they all have 16 gigs or 24 gigs

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/8c1d2ec6-6f60-4a86-8c6f-5e6b5cf8b827)

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/e3d327ed-961d-45d2-9b9b-ede541522dcf)


Runs just fine until 10 minutes.

**Comment by SomethingGettingWrong** [comment]
Hmm random thought... do you have something in your miner to catch a network exception? say if an ISP is blocking your domain for your dev fee? However, In my case my laptop is on same connection. same router and ive tried both wired and wifi .  with it just exiting its an exception thats not being flagged?

**Comment by SomethingGettingWrong** [comment]
how would i give you a coredump?

**Comment by TrailingStop** [comment]
Hi - please wait until tomorrow. I'll release a new beta with some bugfixes. I have also looked into this issue and made some modifications. Let's see how this works first.

Thanks for reporting and you help.

**Comment by SomethingGettingWrong** [comment]
> Hi - please wait until tomorrow. I'll release a new beta with some bugfixes. I have also looked into this issue and made some modifications. Let's see how this works first.
> 
> Thanks for reporting and you help.

Will not mess  with any more today. but can say that  I tried last 3 version of spectrex I think that was all that supported spectrexx same Illegal instruciton. TTYL

**Comment by TrailingStop** [comment]
Hi - can you please let me know what cpu you have? TT print information about it at start, I need to know if TT recognized the supported extended commands correctly. Should look like this:

16:20:21.211   #05 PCI ff:00.0         GenuineIntel Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   8 Cores, 16 Threads
16:20:21.212                           Cache: L1(Data): 32.77 kB, L1(Code): 32.77 kB, L2: 262.1 kB, L3: 16.78 MB/16 Threads, 1.049 MB/per Thread
16:20:21.213                           Extensions: SSE AVX AVX2 AES

**Comment by TrailingStop** [comment]
Hi,

please check out the latest beta and let me know if you still see thew bug.
Thanks

**Comment by SomethingGettingWrong** [comment]
The i7 3770x 3.4 ghz intel CPU now does not crash at 10 minutes and gained 2 percent speed. over the official release thats current.  (wasnt working past 10mins now works) 

The I7 2500k works and  got a percent increase ( wasnt working past 10 mins)

The I7 laptop thens been working entire time with (nvidia gpu) integrated works and got a percent increase.



However, a pc that was working up to 10 mins... wont work with the betas like the rest. 

Here is the problem CPU i5 3570...  that did work and ran for 10 mins....  pictured here in the image but crashed at 10 mins. 
I bleive it should be fixed as well but i think a diffrent bug is happening. 
![i5 3570 worked but crashed after 10 mins](https://github.com/user-attachments/assets/3e6505c9-61c3-44d8-8a58-750fe072720a)


has an issue in the betas 
2024 3 3b4
![2024 3 3b4 doesnt detect spr](https://github.com/user-attachments/assets/62a0905e-68e8-4c73-8760-94db6de8d325)
2024 3 3b5
![2024 3 3b5 doesnt detect spr](https://github.com/user-attachments/assets/b9037946-5d87-400b-a582-e3b1af8c5309)

again all 3 images are same pc and it did run for 10 mins and the betas should fix it.. but im guessing its getting confused as a gpu or something? i dunno

**Comment by TrailingStop** [comment]
looks like TT cannot loa the algo for spectre.  can you please delete the complete TT folder and reinstall the b5?

**Comment by SomethingGettingWrong** [comment]
> looks like TT cannot loa the algo for spectre. can you please delete the complete TT folder and reinstall the b5?

I did it several times. then realized that windows defender was the issue.  I am however recieving alot of lowe difficulty shares on all pc's since the version that quit at 10 minutes. However, you might be aware of that. Since its a completely diffrent related issue im goign to just close this as complete. !
