### ISSUE TITLE
-No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by samdoo46** [TrailingStop/TT-Miner-release#53]
i have followed the steps written in the manual to set up the miner and the wallet but when i execute the start mining file TT miner runs in command promt and then it says -No connection could be made because the target machine actively refused it

**Comment by TrailingStop** [comment]
Hi - this messge comes often if you use a ssl port and do not add ssl to the tt command line (or the other way round).
Can you share any more information about this problem? Just the message i not relly much to debug.

**Comment by samdoo46** [comment]
> Hi - this messge comes often if you use a ssl port and do not add ssl to the tt command line (or the other way round). Can you share any more information about this problem? Just the message i not relly much to debug.
what do you need to solve this problem ?

**Comment by TrailingStop** [comment]
A commandline would be great - you can also dm it.
