### ISSUE TITLE
Question by a noob about your miner. 

### ISSUE THREAD

**Issue by SomethingGettingWrong** [TrailingStop/TT-Miner-release#54]
So i usually just run 
TT-Miner.exe -a spectrex -P spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a.Patrick@us.acc-pool.pw:18061
For spectrx

I would like to mine kawpow on my gpu but with NHASH 

Can you give me a one liner with my info for nicehash?  

is my nichehash mining address 

How would i assemble a oneliner for spectrex above and kawpow on my gpu with that as the payment address? 

TT-Miner -dag-2disk -daginfo -a KAWPOW -P stratum+ssl://3MQ7EXp5Bg1e4ypnuaEDd78AxV9hYKEgrL .kawpow_gpu@kawpow.auto.nicehash.com:443

I see this but dont know how to combien them

Also if i just want to mine spectrex and btc lottery ... -lottery BTC   to the end how would it know what address to pay too?

**Comment by TrailingStop** [comment]
Sure. Can you please run 
tt-miner -l
to get a device list. 
Please let me then know which devices you want to use for kawpow. If you run on intel you can setup the internal iGPU to mine some BTC :)

**Comment by SomethingGettingWrong** [comment]
C:\TT-Miner-2024.3.3b5>TT-Miner.exe  -l
01:18:36.286 ********* TT-Miner - Version: 2024.3.3 - Beta 5 (Jul 25 2024 08:21:53)
01:18:36.286 ********* Log system initialized...
01:18:36.286 ********* Internal event system initialized...
01:18:36.286 ********* Worker threads initialized, using 2 threads...
01:18:36.309 ********* Commandline: TT-Miner.exe -l
01:18:36.618 ********* CPU/Core information
01:18:36.618       CPU/Core devices:   1
01:18:36.618 * #01 PCI ff:00.0         GenuineIntel        Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz   4 Cores, 4 Threads
01:18:36.619                           Cache: L1(Data): 32.77 kB, L1(Code): 32.77 kB, L2: 262.1 kB, L3: 6.291 MB/4 Threads, 1.573 MB/per Thread
01:18:36.619                           Extensions: SSE AVX AES
01:18:36.619
01:18:36.619
01:18:36.619 ********* OpenCl-Devices(GPU) information
01:18:36.619       GPU devices:        1
01:18:36.619 * #00 PCI 01:00.0         Radeon RX 580 Series  8.000 GB / 7.750 GB  SM: 36   2.0
01:18:36.619
01:18:36.619
01:18:36.621 ********* Stop worker threads...
01:18:36.621 ********* Internal event system stopped and destroyed...
01:18:36.621 ********* All threads stopped and destroyed...

**Comment by SomethingGettingWrong** [comment]
I also have an INTEL OPEN CL GPU as well i want to mine btc  on probably so bothwould helpful

**Comment by TrailingStop** [comment]
For spx & kawpow on nh please try this:

TT-Miner.exe -dSP 1 -aSP spectrex -PSP spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a.Patrick@us.acc-pool.pw:18061 -dKA 0 -aKA KAWPOW -PKA stratum+ssl://3MQ7EXp5Bg1e4ypnuaEDd78AxV9hYKEgrL.kawpow_gpu@kawpow.auto.nicehash.com:443

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/440e96fa-8cb6-4662-a9f4-18ccc58e19e5)

**Comment by SomethingGettingWrong** [comment]
it works but 0 hashs lul.. might be ccuz cpu is maxed out let me try with -t1 on the cpu

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/bdafd2f2-0bbc-44f3-98d9-95b38ed223e2)
 yeah i removed the spectrex mining from cpu and getting hashrate now  how do i mine spectrex wiht 1 thread now with the newonelineer config you gaveme?

**Comment by SomethingGettingWrong** [comment]
01:41:50.995 ********* TT-Miner - Version: 2024.3.3 - Beta 5 (Jul 25 2024 08:21:53)
01:41:50.995 ********* Log system initialized...
01:41:50.995 ********* Internal event system initialized...
01:41:50.995 ********* Worker threads initialized, using 2 threads...
01:41:51.612 ********* Commandline: TT-Miner.exe --l
01:41:53.094 ********* CPU/Core information
01:41:53.094       CPU/Core devices:   1
01:41:53.094 * #01 PCI ff:00.0         GenuineIntel         Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   4 Cores, 8 Threads
01:41:53.095                           Cache: L1(Data): 32.77 kB, L1(Code): 32.77 kB, L2: 262.1 kB, L3: 8.389 MB/8 Threads, 1.049 MB/per Thread
01:41:53.095                           Extensions: SSE AVX AES
01:41:53.095
01:41:53.095
01:41:53.096 ********* OpenCl-Devices(CPU) information
01:41:53.096       CPU devices:        1
01:41:53.096 * #00 PCI 00:00.0                 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz  15.92 GB / 0 B       SM: 8    1.2
01:41:53.096
01:41:53.096
01:41:53.100 ********* Stop worker threads...
01:41:53.100 ********* Internal event system stopped and destroyed...
01:41:53.101 ********* All threads stopped and destroyed...

THis is what i woudl like to BTC mine on the IGPU with. 

TT-Miner.exe -t 3 -a spectrex -P spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a@us.acc-pool.pw:18061

**Comment by SomethingGettingWrong** [comment]
kk makes since ill try that. on the AMD I5 combo. 

> Should work with spx as well. you stopped the mining too early. kawpow needs a dag and that must be created. that will need some time - depending on the coin nh selected. So if you give it some more time you will see that it works.
> 
> Limiting threads works only with -t if you mine just a single algo/coin. Now that you add a sewconde algo you need to tell TT for which algo you want to reduce the threads. So please use -tSP 6 to set the threads to 6 for the spx algo

kk ill try this on the i 5 spr/ kawpow amd gpu.

**Comment by SomethingGettingWrong** [comment]
> 01:41:50.995 ********* TT-Miner - Version: 2024.3.3 - Beta 5 (Jul 25 2024 08:21:53) 01:41:50.995 ********* Log system initialized... 01:41:50.995 ********* Internal event system initialized... 01:41:50.995 ********* Worker threads initialized, using 2 threads... 01:41:51.612 ********* Commandline: TT-Miner.exe --l 01:41:53.094 ********* CPU/Core information 01:41:53.094 CPU/Core devices: 1 01:41:53.094 * #1 PCI ff:00.0 GenuineIntel Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz 4 Cores, 8 Threads 01:41:53.095 Cache: L1(Data): 32.77 kB, L1(Code): 32.77 kB, L2: 262.1 kB, L3: 8.389 MB/8 Threads, 1.049 MB/per Thread 01:41:53.095 Extensions: SSE AVX AES 01:41:53.095 01:41:53.095 01:41:53.096 ********* OpenCl-Devices(CPU) information 01:41:53.096 CPU devices: 1 01:41:53.096 * #00 PCI 00:00.0 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz 15.92 GB / 0 B SM: 8 1.2 01:41:53.096 01:41:53.096 01:41:53.100 ********* Stop worker threads... 01:41:53.100 ********* Internal event system stopped and destroyed... 01:41:53.101 ********* All threads stopped and destroyed...
> 
> THis is what i woudl like to BTC mine on the IGPU with.
> 
> TT-Miner.exe -t 3 -a spectrex -P spectre:[qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a@us.acc-pool.pw](mailto:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a@us.acc-pool.pw):18061

as far this one.. -lottery BTC at the end results in nothing but @pause on cmd

**Comment by TrailingStop** [comment]
I do not see the iGPU. If this is a different box please run again tt-miner -l

**Comment by SomethingGettingWrong** [comment]
kk, makes since. I think i got the format right i didnt want to wake my duaghter up. hOw do i mine btc on the rx580? i can transalte after that i think im understanding your setup now on your lines. if you can show me that i think ill just use my own time to figure it out instead of waisting yours whichim so very thankful for

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/7ba38e0e-7ee5-46c8-9853-b69ffb6f173f)
 wierd this has IGPU in it.. i dont understand.

**Comment by TrailingStop** [comment]
You do not waste my time - it is what I here for and I'm happy to help.
for just BTC you can use:
tt-miner -c BTC -P <btcwallet>......etc

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/01ed59b6-9cd9-4c5e-a6ae-c68e2e4d7e8f)

**Comment by SomethingGettingWrong** [comment]
hmm okay. well lets say i want to just solo mine btc on the RX580 and spectere on the cpu how would i change this If my btc solo pool was this 
 stratum+tcp://solo.ckpool.org:3333  1PKN98VN2z5gwSGZvGKS2bj8aADZBkyhkZ

TT-Miner.exe -dSP 1 -aSP spectrex -PSP spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a.Patrick@us.acc-pool.pw -dKA 0 -aKA KAWPOW -PKA stratum+ssl://3MQ7EXp5Bg1e4ypnuaEDd78AxV9hYKEgrL.kawpow_gpu@kawpow.auto.nicehash.com:443

**Comment by TrailingStop** [comment]
try just this:

TT-Miner.exe -dSP 1 -aSP spectrex -PSP spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a.Patrick@us.acc-pool.pw -dB 0 -cB BTC -PB 1PKN98VN2z5gwSGZvGKS2bj8aADZBkyhkZ.btc_gpu@solo.ckpool.org:3333


this is the 'idea' behind tts way to support more than a single algo/coin:

if you use a single algo it is easy. just use:
-d (for device-selection) -a or -c (for algo or coin) and -P (for all information to connect to the pool for this coin/algo)

If you use more than a single algo/coin you need to tell TT which information belong together. for That just pick one or more capital letters and append them to the option.

Like "SP" for spectre, "KA" for KAWPOW - or "B" for BTC- you can use whatever you want as long as it is a capital letter.

that makes then (for spectre as sample):

-dSP 1 -aSP spectrex -PSP spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a.Patrick@us.acc-pool.pw:18061

hope this brings some more light into it? Let me know if you have any questions.

**Comment by SomethingGettingWrong** [comment]
You cleared it all up brother closing now. THanks!

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/c2b5c3bc-9801-4b0f-a2b4-6729f7806c15)

You can keep this closed but was gonna say i guess my IGPU is too old it tries to start.. but maybe it cant do it and power monitor same time lul!!!!

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/d4f7de61-27cf-4bb2-b593-aaa156088997)
Yeah i entered in correctly  both start mining but niether work togahter. I guess the IGPU just cant do it for some reason quite wierd

**Comment by TrailingStop** [comment]
Not sure if both devices are really OpenCL. My guess is that the first one is ther CPU using opencl, the second might be the native CPU - without the opencl driver - not the iGPU!

**Comment by SomethingGettingWrong** [comment]
ohhhh okies well its a driver issue not to worry. jus tleave this closed. stuffs old anyway if people are having an issue they will worry about it in a "new issue"

**Comment by TrailingStop** [comment]
Looks good. I do not see you device assignment, so I do not know how TT assigned devices to algos.

**Comment by TrailingStop** [comment]
wait - you should be able to use the opencl driver of the cpu to mine BTC, but keep in mind that spectre will also use the same cpu - just not using the opencl.

**Comment by SomethingGettingWrong** [comment]
oh i think i figured out whats going on.... this is wierd.  its getting the cpu and igpu mixed up .. some how 

so 00 is the gpu and 01 is the cpu... 

but wieredly enough... 00 is the cpu... when i just pick the  -d -c -p  

If i flop them it tries to start.. on one but not the other... for example 

rem TT commandline
TT-Miner.exe -dSP 0 -aSP spectrex -PSP spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a.Patrick@us.acc-pool.pw:18061 -dBTC 1 -cBTC BTC -PBTC 1PKN98VN2z5gwSGZvGKS2bj8aADZBkyhkZ.btc_gpu@solo.ckpool.org:3333
pause

will freeze

but 
rem TT commandline
TT-Miner.exe -dSP 1 -aSP spectrex -PSP spectre:qz3sj8z6c40x00vvy8slzkxfrmjde4jvtk5mg9hcn4hww4mslqwsq82yfxc0a.Patrick@us.acc-pool.pw:18061 -dBTC 0 -cBTC BTC -PBTC 1PKN98VN2z5gwSGZvGKS2bj8aADZBkyhkZ.btc_gpu@solo.ckpool.org:3333
pause

Swapping the devices... makes it go further and start to mine..

But if i only run one at a time... and pic the device... it wont work on  either...

**Comment by SomethingGettingWrong** [comment]
![image](https://github.com/user-attachments/assets/674d8cb6-4d95-42ef-bbb9-9fc2545a3fb2)
![image](https://github.com/user-attachments/assets/83b4499d-3fd6-4d32-9d49-be007a4cee78)

**Comment by TrailingStop** [comment]
That is because TT does NOT have an algo for native CPU, only for cuda & opencl.

**Comment by SomethingGettingWrong** [comment]
okies thanks again and again you have me for life on  6 gpus and 5 cpus thanks

**Comment by TrailingStop** [comment]
as always I'm happy to help!

**Comment by SomethingGettingWrong** [comment]
How long till astrobwt3 heavyahas sha3 spetrex algo gets an opencl gpu version? I seen a ton of astrobwt3 dero miners?

**Comment by TrailingStop** [comment]
GPU Miners Astro?

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
