### ISSUE TITLE
Disabled Onboard audio Increased hashrate.

### ISSUE THREAD

**Issue by SomethingGettingWrong** [TrailingStop/TT-Miner-release#55]
So this isnt an issue and i plan on closing this as soon as i get your response.
I honestly didnt know how to contact you. 
Im not sure if people are aware but on my cpu.. that got 1.78 kh/s .. I bought a dedicated soundcard. this took a load off my cpu.. 

i get 2.1kh/s now on my cpu.. So if people have dedicated minng rigs. You should note to disable thier onboard sound. If i had a way to contact you I would have. You dont have an email do you?

**Comment by SomethingGettingWrong** [comment]
Random I have 8 logical cores (4 real cores) and 8 mb of l3 cace 1 mb of l2 cache.. It starts with 2 threads by default. Why not 4? 

I put in -t 4 it still does only 2. im assuming cache is the issue?

**Comment by TrailingStop** [comment]
Hi,

will check later today. My mail: droste@TradeProject.de - or use my discord: https://discord.gg/kSvbBruF

**Comment by SomethingGettingWrong** [comment]
kk thanks
