### ISSUE TITLE
CPU is mining at lower hashrate then before

### ISSUE THREAD

**Issue by CoFfEe0LaVa** [TrailingStop/TT-Miner-release#56]
I am running Ryzen 3 1200 on Ubuntu server
Don't know if its miner or the pool but I still want answers
the pool is https://spectre.acc-pool.pw with SPR
and in first week it was mining at 1kh/s then I stoped it for some reasons and the next time I started miner again and this time was running at 1h/s then was progressing up to 75h/s and now put 200h/s
the time when was up to 75h/s was maybe bc I was running form Proxmox VM and now is pure Ubuntu server
Don't know what happened?

**Comment by TrailingStop** [comment]
Hi - difficult to help from the distance. There is no code in the miner that reduces hashrate after time. Here some ideas that could affect the hashrate:

1- other processes/apps are running and using cpu 
2- lower available ramsize
3- huge pages are not available
4- hardware/software changes?
5- different number of threads used by the miner? (option -t x)
Best I can advise is to reboot the machine and make sure no other process is started that is not required.

**Comment by CoFfEe0LaVa** [comment]
1-just the miner and I checked with htop
2-Not enough or To much ram you mean , I have 16GB ram
3-not sure about that , is it something in bios or just a cpu instruction or future?
4-fist UB server with 1kh/s then Proxmox with 75h/s then UB server again but with 200h/s
5-it starts by saying that is using 2 threads and it gets like a minute to start then when starts it needs 5 minute to get form 24 h/s to 200 h/s

Rebooting is not going to do anything and I checked htop

also question , is running root (with sudo -i) possible problem

**Comment by TrailingStop** [comment]
Hi - no need to run as root if you do not need GPU OC - but it does not hurt. The 2 threads showing at start are needed to manage communications and mining (multithreading) operation of TT. But you can still use the cores for mining.
Can you please show the commandline you use?

**Comment by CoFfEe0LaVa** [comment]
root@gemmine1k:~# cd /root/TT-Miner-2024.3.2
root@gemmine1k:~/TT-Miner-2024.3.2# ./TT-Miner -a spectrex -P qqmns7lycknxaaa2nak7sq6p0uzhg92w3u5gf4adecfc49nder445606h53ck.rig@acc-pool.pw:18061
11:26:48.257 ********* TT-Miner - Version: 2024.3.2 (Jul 11 2024 11:11:29)
11:26:48.257 ********* Log system initialized...
11:26:48.257 ********* Internal event system initialized...
11:26:48.257 ********* Worker threads initialized, using 2 threads...
11:26:48.270 ********* Commandline: ./TT-Miner -a spectrex -P qqmns7lycknxaaa2nak7sq6p0uzhg92w3u5gf4adecfc49nder445606h53ck.rig@acc-pool.pw:18061

What do mean by command line ? this^ or bash os something?

**Comment by TrailingStop** [comment]
Yes. this is what I meant. Can you please send a screenshot of htop if TT is running? You can also check the single-core performance by appending -t 1. Hashrate should be in the 500H ballpark.
