### ISSUE TITLE
2023.1.1 (Windows) Creating kernel for GT1030 fails 

### ISSUE THREAD

**Issue by UselessGuru** [TrailingStop/TT-Miner-release#6]
10:14:42   #0 CudaId-0 PCI 11:00.0 nVidia  NVIDIA GeForce GTX 1660 SUPER  6.000 GB / 1.679 GB  SM: 22  Compute: 7.5
10:14:42 * #1 CudaId-1 PCI 12:00.0 nVidia  NVIDIA GeForce GT 1030         2.000 GB / 287.4 MB  SM: 3   Compute: 6.1
10:14:42   #2 CudaId-2 PCI 16:00.0 nVidia  NVIDIA GeForce GTX 750 Ti      2.000 GB / 1.389 GB  SM: 5   Compute: 5.0
[...]
10:14:42 ********* Start API Monitor Listener
10:14:42 ********* Start mining
10:14:42 ********* Mining fee for 'Vkax': 2.00%
10:14:42 ********* Start worker loop...
10:14:42 Pool[VKAX-0]:  Connecting to: stratum+tcp://mike.eu.mine.zpool.ca:5356
10:14:42 Pool[VKAX-0]:  Connected to: mike.eu.mine.zpool.ca:5356 - IP4/IP6: 198.50.168.213
10:14:42 Pool[VKAX-0]:  Set pool extra nonce to: 0x690000A1
10:14:42 Pool[VKAX-0]:  Difficulty changed from 0 H to 1.310 kH
10:14:42 Pool[VKAX-0]:  Received new job#: 250
10:14:42 Pool[VKAX-0]:  Working on Block#: 107783
10:14:42 Coin[VKAX]:    Kec-Smd-Skn-Grt-Blk-CnTrt-Bmw-Luf-Jh-Shv-Cub-CnLt-Eco-CnTrtLt
**10:14:42 Krnl[01-VKAX]: Create Kernel (A017#0-61) for NVIDIA GeForce GT 1030**

-> Back to prompt

GT1660Super and GTX750Ti work well

**Comment by TrailingStop** [comment]
I suspect the 1030 does not have enough memory - I'll run a quick test to verify here.
Thanks for the bug report.

**Comment by TrailingStop** [comment]
Hi- can you please try with the new version (2023.1.3) if this problem still exists?
Thanks.

**Comment by UselessGuru** [comment]
Problem is fixed in 2023.1.4
